### ISSUE TITLE
Outdated 'isarray' package

### ISSUE THREAD

**Issue by feimosi** [pillarjs/path-to-regexp#101]
There's already v.2.0.1
https://github.com/juliangruber/isarray/releases

**Comment by blakeembrey** [comment]
IIRC, 2.0 was a targeted release to include deprecation messages from NPM. Is there a reason to upgrade?

**Comment by feimosi** [comment]
I don't see the changelog there, so I can't tell you. Nonetheless here's the thing:
- you're depending on a 0.0.1 version, which can hardly be called an alpha (based on semver)
- it's always good to try to keep the dependencies most up to date possible
- there's also v.1.0.0 if you're concerned about the 2.0

I just raised my thoughts here.

BTW. You could have waited for my response before closing the issue (eh where have the good OSS manners gone these days).

**Comment by blakeembrey** [comment]
> You could have waited for my response before closing the issue

It's difficult for me to keep up with hundreds of repos. If a decision is made, I'll close it. Closed doesn't mean you can't respond. The flipside is keeping it open, and if you don't respond (like many people) then I have dozens of issues open across dozens of repos which really should be closed. The answer is probably a better GitHub dashboard, but until then I'll close it if I feel it's resolved.

I'd be open to upgrading to 1.0 if you want to submit a PR.

**Comment by feimosi** [comment]
Sure, I understand, but I've seen other projects using tags to mark PRs waiting for an answer. I just think closing the issue immediately can discourage a whole lot of contributors, especially the first-time ones. If this approach works for you, then you should at least nota that in the comment / PR template.

Anyway, I'll do the PR 👍

**Comment by blakeembrey** [comment]
Thanks, I understand. I'll try and keep that in mind. I do agree I closed this one prematurely, sorry! I thought we were using 1.0, not 0.x, so didn't even think a PR would be necessary. We'll be removing this dependency in a future version too, just haven't had a need to make a new major yet. It's probably time to just go for a major with just `isarray` removed, but I'll think on that separately.

**Comment by feimosi** [comment]
Good idea! The browser support for `Array.isArray` seems already descent.
