### ISSUE TITLE
Make a route that will work with ending slash or not?

### ISSUE THREAD

**Issue by ccuilla** [pillarjs/path-to-regexp#103]
I'd like to create a route definition that works with and without the ending slash. For example:

'/entity/:id\/*'

What I want here is for the router to accept both of the following:

http://localhost:3000/entity/foo

and

http://localhost:3000/entity/foo/

Where foo is mapped to the id parameter.

I've tried a couple options:

'/entity/:id\/*'
'/entity/:id(\/{0,1})'

Is this even possible?

**Comment by blakeembrey** [comment]
It already does it by default. See https://github.com/pillarjs/path-to-regexp#usage.

**Comment by ccuilla** [comment]
Okay. I assume you're referring to the `strict` option? I wasn't quite sure how to interpret that. Thanks!

**Comment by blakeembrey** [comment]
Yes, `strict` is the one I was referring. Let me know if there's a better way to word it that would make sense to you.
