### ISSUE TITLE
Make string+var pair optional?

### ISSUE THREAD

**Issue by coluccini** [pillarjs/path-to-regexp#105]
Hi, one quick question. Having an url likes this: 

`/list/cat-:catNumber/subcat-:subcatNumber` (where cat- and subcat- are strings)

Is there a way to make the pairs be optional? I mean, if I have not defined :subcatNumber, just point to /list/cat-:catNumber? I want to avoid having to 

`/list/:catNumber` -> params={{ catNumber: 'cat-1' }}`

Thanks!

**Comment by blakeembrey** [comment]
I don't really understand the question, can you give a solid rlexample of what you're trying to do? Parameters themselves can be made optional with a question mark at the end.

**Comment by coluccini** [comment]
Sorry, let me see if I can be a little bit more clear this time.
I'm trying to achieve something like this:

`list/:var1?/:var2?/:var3?/:var4?`

But I need to have the name of varX concatenated to the varX value in the resulting url, so having this:

`<Link route="list" params={{ var1: A, var3: Y }}>`

Should result in this url:

`/list/var1-A/var3-Y`

I tried this:

`list/var1-:var1?/var2-:var2?/var3-:var3?/var4-:var4?`

But with the previous example results in:

`/list/var1-A/var2-/var3-Y/var4-`

Is more clear now?

**Comment by blakeembrey** [comment]
You can use an array of strings or regular expressions. It's not possible to magically make the text before the parameter become optional also.

**Comment by coluccini** [comment]
Ok, I kind of expect that, I'll find a different approach to the issue but just wanted to be sure there were no path-to-regex way to do it. Thanks for your answer and for this magnificent library!

**Comment by blakeembrey** [comment]
Nope, sorry. The best thing is either plain RegExp, messy array or combination something like `/list/(var1-[^/]+)`. Feel free to leave a comment when you come up with your solution in case someone else has a similar issue in the future.
