### ISSUE TITLE
remove the dependency by isarray

### ISSUE THREAD

**Issue by gitsupersmecher** [pillarjs/path-to-regexp#107]
I was taking a dependency by this library in my project. I do like the library. You guys, have done a very nice job with it. Congrats! My feedback is regarding taking a dependency by isarray. I do not understand why for 3 lines of code you need to take a dependency by such a small library. I do believe in code re-usability, but I think that fragmentation in web libraries is a bigger problem than reusing code fragments. There is a border that clearly should be evaluated case by case on this topic, but overall I would recommend to remove the dependency by isarray, in this case. 

Thanks!

**Comment by blakeembrey** [comment]
Please search existing issues for previous discussions. It will be removed when a 2.0 is released, but can not be removed before because that would break backward compatibility.
