### ISSUE TITLE
Pass a different value than the match?

### ISSUE THREAD

**Issue by coluccini** [pillarjs/path-to-regexp#108]
Hi!
I would like to use a string to define a match but if matched return an ID related to that string:
Ex:
```javascript
var re = pathToRegexp('/:type(rent)?/:term', keys)
re.exec('/rent/house')
//=> ['/rent/house, 1, 'house']

var re = pathToRegexp('/:type(sale)?/:term', keys)
re.exec('/sale/house')
//=> ['/sale/house, 2, 'house']
```
It is possible to define a different returned value that the one returned from the match using a Custom Match Parameters?

**Comment by blakeembrey** [comment]
No. You can just map it separately. E.g. `{ rent: 1, sale: 2}[params[1]]`.

**Comment by coluccini** [comment]
Ok. Thanks!
