### ISSUE TITLE
Parameter partial binding support?

### ISSUE THREAD

**Issue by ThisSentenceIsFalse** [pillarjs/path-to-regexp#109]
It would be nice to have some out-of-the-box utilities to gradually complete the parameters for a path, such as: 

```
bindParameters('/bla/:foo/:type', {type: 'baz'}) -> '/bla/:foo/baz'
```

I would like to mention upfront I do realize how I could use the `compile` API and a form of 'currying' to obtain a similar result. However, this approach would yield a new function on each assignment. I'm working on a [React](https://facebook.github.io/react/) application, and passing around function references in React Components makes it slightly more difficult to implement diffing logic. 

Raw strings, OTOH, usually behave quite nicely wrt to comparison, and they seem sufficient to fully specify a path. It also looks like most of the work is already done within the parse function and the algorithm to construct a path with all required parameters. Therefore exposing such functionality with a new utility shouldn't be a daunting task, and anyone needing it wouldn't be worried about unreliably interpreting the tokens with their own procedures.

Of course, some quirks are unavoidable with unnamed or repeat parameters, but in my very subjective opinion, the benefit outweighs them.

**Comment by blakeembrey** [comment]
I'm welcome to accepting a PR demonstrating the feature. Is there any benefit in having a currying function over returning a new partially filled in string?

**Comment by ThisSentenceIsFalse** [comment]
I feel currying would be less ambiguous when faced with exotic paths as in the example below:

```
// Currying example
const pathToRegexp = require('path-to-regexp');
const unusualPath = '/(.*)/bla/(.*)';

console.log(pathToRegexp.parse(unusualPath));
// [ 
//  {name: 0, prefix: '/', delimiter: '/', optional: false, repeat: false, partial: false, asterisk: false, pattern: '.*'},
//  '/bla',
//  {name: 1, prefix: '/', delimiter: '/', optional: false, repeat: false, partial: false, asterisk: false, pattern: '.*'}
// ]

const compile = pathToRegexp.compile(unusualPath);
const params = {0: 'foo/bar', 1: 'baz'};

// The following two should yield the same path '/foo/bar/bla/baz'
// Notice that it's easy to keep the original parameterized path through
// the calls to 'curry', so indices used for unnamed parameters are preserved
const firstCurriedPath = compile.curry({0: 'foo/bar'})({1: 'baz'});
const secondCurriedPath = compile.curry({1: 'baz'})({0: 'foo/bar'});

// I cannot see a clean way to do this with the 'bindParameters' format:
const partialPath = bindParameters(unusualPath, {0: 'foo/bar')); // should be '/foo/bar/bla/(.*)'

console.log(pathToRegexp.parse(partialPath));
// ...
// {name: 0, prefix: '/', delimiter: '/', optional: false, repeat: false, partial: false, asterisk: false, pattern: '.*'}

const fullPath = bindParameters(partialPath, {1: 'baz'}); 
// the '1' index doesn't exist according to the semantics of 'parse' above,
// so this bind doesn't really do anything!
```

Then again, I can hardly believe multiple unnamed parameters are common; I would never do this sort of binding, let alone performing it outside the confines of **one** module. In my opinion, currying would be of benefit mainly with named parameters.

Also, implementing the first sort of currying in the package is somewhat superfluous, since it's rather simple to roll your own version without the 'one-size-fits-all' hassle:

```
import pathToRegexp from 'path-to-regexp';

let binderProto;

function pathBinder(compiledPath, params) {
  return Object.create(binderProto, {
    compiledPath: {
      value: compiledPath
    },
    params: {
      value: params
    }
  });
}

binderProto = {
  setParams(nextParams) {
    return pathBinder(this.compiledPath, {...this.params, ...nextParams});
  },
  yieldPath() {
    return this.compiledPath(this.params);
  }
};

export default function(path, initialParams) {
  return pathBinder(pathToRegexp.compile(path), initialParams);
};
```

I'm slightly stuck with quite a few chores in this period, will try to reach back with a PR after the weekend.

**Comment by blakeembrey** [comment]
I'm going to keep the current API how it works today. If people want currying, it should probably be done in their own libraries for now. The way I'd do something like this is:

```js
const toPath = compile(...)

const curried = (() => {
  let arg = {}

  return params => {
    if (params === undefined) return toPath(arg)
    arg = { ...arg, ...params }
  }
})()
```
