### ISSUE TITLE
Strict should not allow a trailing slash

### ISSUE THREAD

**Issue by posva** [pillarjs/path-to-regexp#112]
Hello,

First, thanks a lot for creating `path-to-repexp`, we use it to handle paths in vue-router and it makes things pretty easy 🙂 

When using `strict: true`, a path will only match with a trailing slash:

`/foo` -> `/foo/` but no `/foo`

but this looks strange because I see no way to **force a path not to have a trailing slash**

_?_ -> `/foo` but not `/foo/`

IMO, it would make more sense to allow the user to force the slash by simply appending it to the route: `/foo/` -> `/foo/` but not `/foo`

Now, I know this is a breaking channge but still wanted to know your thoughts about this because I couldn't find any previous issue about the topic

**Comment by Haeresis** [comment]
I every one!

I actually this issue : https://github.com/vuejs/vue-router/issues/1443 when I use `vue-router` that use `path-to-regex` to work.

A solution appear to simply set `pathToRegexOptions: { strict: true }` to resolve this issue but what I see it's the reverse of what I want!

by default:
- **standard case** : `/foo/` -> `/foo/` and `/foo` work

using `pathToRegexOptions: { strict: true }`:
-  **curious case (I have)** : `/foo/` -> `/foo` work | `/foo/` not 
-  **expected case (I want)** `/foo/` -> `/foo/` work | `/foo` not 

To comparison, using Express with Node.js with the 'strict mode' option and it work in this way
-  **expected case** `/foo/` -> `/foo/` work | `/foo` not

**Comment by blakeembrey** [comment]
I don't follow this issue or understand the next comment, sorry. This is already how it works. See the test case: https://github.com/pillarjs/path-to-regexp/blob/e97122de4189f8596b81a3b19d9f338474cf1a45/test.ts#L116-L132. If I'm misunderstanding the request, please let me know.

**Comment by posva** [comment]
oh, what the hell 😆 
My bad, sorry for the noise, you're right, that's how it works right now
