### ISSUE TITLE
Trailing Delimiters and the Root

### ISSUE THREAD

**Issue by pshrmn** [pillarjs/path-to-regexp#116]
Previously, the root pathname (`/`) would match everything when `end = false`. With the release of `v2.0.0`, that is no longer the case.

```js
// 1.7.0
const re1 = PathToRegexp('/', [], { end: false });
re1.exec('/'); // ["/", index: 0, input: "/"]
re1.exec('/test'); // ["", index: 0, input: "/test"]

// 2.0.0
const re2 = PathToRegexp('/', [], { end: false });
re2.exec('/'); // ["/", index: 0, input: "/"]
re2b.exec('/test'); // null
```

I believe that this is related to the trailing delimiters change in v2, but to be perfectly honest, browsing through the diff for https://github.com/pillarjs/path-to-regexp/commit/9d4cbd91698529e719fc00d20dc87aa382db54ee, I wasn't positive where this change was made.

I was looking into updating React Router to use v2, but having `/` match any pathname is a pretty core requirement. I'm not sure if the current implementation would be considered a bug or if this is the desired behavior. Any feedback would be appreciated.

**Comment by pshrmn** [comment]
These are the regular expressions returned by the above calls:
```js
/^(?:\/(?=$))?(?=\/|$)/i    // 1.7
/^\/(?:\/(?=$))?(?=\/|$)/i  // 2.0
```
Where the only difference is that the latter requires the string to begin with a forward slash, while that is stripped from the former.

I took a closer look at the code, and the change is here https://github.com/pillarjs/path-to-regexp/commit/9d4cbd91698529e719fc00d20dc87aa382db54ee#diff-168726dbe96b3ce427e7fedce31bb0bcR334.

The conflict appears to be caused by the requirement that the first character is a forward slash that is followed either by another forward slash or the end of the string (the positive lookahead inserted because `end=false`). The above regular expression from v2 matches both `/` and `//test` but not `/test`.

I'm not sure what the best approach here would be. Would you consider this a bug? It is a pretty breaking change from React Router's perspective, but obviously React Router isn't the only package that uses `path-to-regexp`. I don't know if others also expect `/` to match all paths. Should there be a special case for a single forward slash? This issue doesn't exist with

**Comment by blakeembrey** [comment]
A single `/` is a trailing delimiter and this was a 2.0 so breaking changes are expected. It is documented in the changes: https://github.com/pillarjs/path-to-regexp/blob/master/History.md#200--2017-08-23. It was an intentional change and not something I intend to reverse too quickly since behaviour that is different to user input seems confusing to me - I'd consider the old behaviour a bug/convenience over incorrect user input. I realise that, also, some people may be using this as a "feature" (again, why it was changed as a major version). If you need backward compatibility with specifically `/` only and not all the `/test/`, `/:foo/` trimming the trailing slash, you could special case it in your own code. Otherwise, if you'd like to match everything, why not use an empty path?

**Comment by blakeembrey** [comment]
I can also make it a flag easy enough (e.g. "strip trailing delimiter path match").

**Comment by pshrmn** [comment]
We can probably make it a special case. Thinking about it some more, `/test` should probably be considered a sibling of `/`, not a descendant, so the new behavior makes sense.

I think that I'll close this for now and only re-open if there isn't a satisfying workaround. Thanks for the quick feedback!

**Comment by blakeembrey** [comment]
No problem, I'm glad that it makes sense once we get the reasoning out 😄  It was certainly a behaviour I considered a mistake and needed to group into a major release to get rid of it. Let me know if I can clarify the history, I can see how it's hard to catch that a single `/` will no longer be matching `/test`.

**Comment by blakeembrey** [comment]
Also, is `/` with `end: false` fairly common in React Router? Could you promote using an empty path instead? With my understanding of React Router, you only used non-ending mode with `Route` when `exact = false` and if the user expected to mount a component as "everything" (hence using `/`) couldn't they just not use the `Route` component at all?

**Comment by pshrmn** [comment]
The current implementation uses `end=false` (aliased as `exact`) by default. It was done out of convenience for nested `<Route>`s, but we've determined it was a mistake and in v5 we'll switch to `end=true` by default.

A `<Route>` with no `path` is meant to match every location. This is used fairly frequently as a means of injecting some location/route matching props into a component (e.g. `<Route component={ThingThatNeedsProps} />`). The `component` only renders when `path-to-regexp` matches the current location.

With `v1.7.0`, when there is no path, we could use `/` and that would match every route, so the `component` would always be rendered.

For `v2.0.0`, we'll probably have to switch that to an empty string. There might need to be a special case added, but it shouldn't be too much effort. This might mess with some people's expectations, but I think that as long as we sufficiently document it, the change shouldn't be too painful.
