### ISSUE TITLE
String with 2 dashes not matching

### ISSUE THREAD

**Issue by coluccini** [pillarjs/path-to-regexp#118]
Hi!
I'm having a weird issue with the following path: `/rent/:property_type?/estado-de-:region`.

It matches `/rent/flat/estado-de-barcelona` when used on the client side but it doesn't on Express 4... The issue seems to be with the 2 dashes on `estado-de-`, cause if I change it to just `estado-` it works on both places. It also works if I do this `/(estado-de-):region`, but I don't want to have this as a captured group. 

Could be an Express related issue? There's any other option beside grouping the string?

Thanks!

**Comment by blakeembrey** [comment]
Express.js uses a buggy 0.1.x version of `path-to-regexp`, so probably. However, I can't replicate your issue in 0.1.7 of `path-to-regexp` which is used by Express. Are you sure you don't have something else going on? This is the regexp I get with Express and it works:

```js
/^\/rent(?:\/([^\/]+?))?\/estado-de-(?:([^\/]+?))\/?$/i.test('/rent/flat/estado-de-barcelona')
```

**Comment by coluccini** [comment]
Yep. It's was an issue related to a mixed routing configuration 😞… sorry to bother you!
