### ISSUE TITLE
Some inconsistencies between 1.x and 2.0

### ISSUE THREAD

**Issue by EvHaus** [pillarjs/path-to-regexp#119]
After upgrading from 1.7.0 to 2.0.0 we're having some issues processing paths. The following code:

```javascript
import pathToRegexp from 'path-to-regexp';

const rule = '/d/view/:code/shift/';
const url = '/d/view/dm2/shift';
const keys = [];
const re = pathToRegexp(route, keys, {end: false});
const matches = re.exec(url);
console.log(matches);
```

in 1.7.0 it returns:

```javascript
// console.log(matches);
[ '/d/view/dm2/shift',
      'dm2',
      index: 0,
      input: '/d/view/dm2/shift' ]
```

but in 2.0.0 it returns:

```javascript
// console.log(matches);
null
```

**Comment by blakeembrey** [comment]
Did you read the changelog? Please read the changelog before making an issue, this is documented already: https://github.com/pillarjs/path-to-regexp/blob/master/History.md#200--2017-08-23. A major version change usually entails breaking changes.

**Comment by EvHaus** [comment]
I see. I did read through the changes, but somehow didn't relate this issue to that change. Thanks for the quick response.

**Comment by blakeembrey** [comment]
I see. Feel free to update the changelog if you have a clearer way to relate it to your issue 😄
