### ISSUE TITLE
How can I convert url back into params  ?

### ISSUE THREAD

**Issue by eromoe** [pillarjs/path-to-regexp#121]
The example doesn't tell about this, 

The feature I mean is:
```
import pathToRegexp from 'path-to-regexp'

const docAnnotatorPath = pathToRegexp.compile('corpus/:corpusId/doc/:docId/annotator')

const params = {corpusId:1, docId:2}
const url = docAnnotatorPath(params )

// something like
const params2 = docAnnotatorPath.parse(url)

// true
params2  == params 

```

**Comment by frenzzy** [comment]
```js
const keys = []
const re = pathToRegexp('corpus/:corpusId/doc/:docId/annotator', keys)

const match = re.exec(url) // <==

const params = !match ? {} : match.slice(1).reduce((acc, val, idx) => {
  acc[keys[idx].name] = val
  return acc
}, {})

console.log(params) // => { corpusId: '1', docId: '2' }
```

**Comment by eromoe** [comment]
It looks complicate, why not put this into `path-to-regexp`  like `somePattern.parse` I mention in title.

**Comment by blakeembrey** [comment]
@eromoe You can use something like https://www.npmjs.com/package/path-match if you'd like. Not everyone maps the parameters, but I'll keep it in mind for the future.

**Comment by eromoe** [comment]
No named parameters return  list, named parameters return dict . 
How about  `lst, dict = somePattern.parse(url)` ?

It is reasonable  and convenient to embed in a path lib I think. 
Hope this would add in future.

**Comment by blakeembrey** [comment]
@eromoe What exactly are you trying to do? It's possible to add it anywhere, including using it from `path-match` directly since that matches the functionality you're looking for.

**Comment by eromoe** [comment]
Yeah, I know.  I just mean it would be nice there only one lib handle all url operation,  to become a good standard to manipulate url in frontend.

**Comment by blakeembrey** [comment]
It's not entirely as simple as that solution, since you'd need to also handle repeat parameter and valid decoding, like what `path-match` does, to ensure you can rebuild the same URL. For the most part however, that's all that is needed for consumers. If you can share what you're trying to do, though might be helpful to find the best solution for you.
