### ISSUE TITLE
conditional dash

### ISSUE THREAD

**Issue by PedroEsperanca** [pillarjs/path-to-regexp#122]
I'm trying to resolve routes like:
`/product/:name?-:id` 

that would allow routes like:
```
/product/wtv-3652672
/product/3652672
```
But this does not seem to work.
What's the recommended way to conditionally include dashes ?

**Comment by frenzzy** [comment]
Maybe use array in this case?
`['/product/:id', '/product/:name-:id']`

**Comment by blakeembrey** [comment]
You can use an array as @frenzzy recommends, or you can use a regexp matching group. There's no other way to specify that you have a relationship between `:name` and `-`.
