### ISSUE TITLE
Invalid group error with group immediately after forward slash

### ISSUE THREAD

**Issue by trss** [pillarjs/path-to-regexp#126]
The second example at https://www.npmjs.com/package/path-to-regexp#parameters doesn't work.
```
> var pathToRegexp = require('path-to-regexp')
undefined
> var re = pathToRegexp('/(apple-)?icon-:res(\\d+).png')
SyntaxError: Invalid regular expression: /^\/(?(?:([^\/]+?))-)?icon-(?:(\d+))\.png\/?$/: Invalid group
```
Node: v6.11.4
NPM: 5.3.0
path-to-regexp: 2.0.0

**Comment by blakeembrey** [comment]
I'm pretty sure you aren't using any recent version of `path-to-regexp` if this doesn't work. It's been a working test case for 2 years: https://github.com/pillarjs/path-to-regexp/blame/1e2f2ed03a8c8aff811ae0c696d8c8f55df7f37c/test.ts#L1753.

**Comment by blakeembrey** [comment]
The only place I can replicate this is from `0.1` and I'm pretty confident there isn't a way to resolve it properly there otherwise it would have been.

**Comment by trss** [comment]
Sorry, my bad. You're right and thanks to your hint I found https://github.com/expressjs/express/issues/3419 to be the actual problem.

**Comment by trss** [comment]
Also, a bigger surprise for me is, `npm view path-to-regexp version` says 2.1.0 where the actual version installed is 0.1.7! And this I happened to find by the following convoluted method:
```
npm install express
npm install path-to-regexp
npm rm path-to-regexp
npm list path-to-regexp
```
which gives me the following:
```
some_dir
└── express@4.16.2

npm ERR! extraneous: path-to-regexp@0.1.7 some_dir/node_modules/path-to-regexp
some_dir$  npm view path-to-regexp
```
I know the right place to discuss this would be https://github.com/npm/npm but wanted to mention it here nevertheless.
