### ISSUE TITLE
How to split out two params in one path segment 

### ISSUE THREAD

**Issue by joenil** [pillarjs/path-to-regexp#128]
In this case `/center/:uid_:aid` matched `/center/123_1`, and the result that I want is:
```
{uid: 123, aid: 1}
```
Is it available?

**Comment by frenzzy** [comment]
`/center/:uid(\\d+)_:aid(\\d+)`

**Comment by blakeembrey** [comment]
I'm not 100% clear on the question since it works as in OP, but if you need to restrict it to only numbers matching you can use the example above from @frenzzy. If this doesn't resolve your query, can you try asking again here for what you want to do?
