### ISSUE TITLE
Consecutive optional params are not matched as expected

### ISSUE THREAD

**Issue by thetutlage** [pillarjs/path-to-regexp#131]
I tried creating a regex for the following expression and it's not matching to what I expected. 

```js
const re = pathToRegexp('/foo/cat/:id?:format?', keys)
const matched = re.test('/foo/cat')

// returns false
```

Maybe  that is how the library is expected to work, but just wanted to make sure and get some ideas on what is best approach of creating a regular expression with consecutive optional params, without a `/` in between.

Live example on [runkit](https://runkit.com/embed/4z7dde0eercx)

**Comment by blakeembrey** [comment]
That's the expected behaviour. It's documented in the README, but feel free to send a PR to improve those docs (https://github.com/pillarjs/path-to-regexp#optional).

**Comment by blakeembrey** [comment]
If you can provide some examples of what you want to do, I can provide some ideas of how to do it. Right now I'm not quite sure what you're after, sorry.

**Comment by thetutlage** [comment]
Not sure how is that the expected behavior just by reading the docs.

As per the route `/foo/cat/:id?:format?`. `id` and `format` are optional, which means `/foo/cat` should match, whereas it returns false

**Comment by thetutlage** [comment]
@blakeembrey Can I expect a response on same?

**Comment by blakeembrey** [comment]
It says it right in the README, please submit a PR if you'd like to clarify it:

> Tip: If the parameter is the only value in the segment, the prefix is also optional.

Your route would match `/foo/cat/` not `/foo/cat` - it's not the only parameter in the segment.

**Comment by blakeembrey** [comment]
If you'd like help on something in particular, please provide some examples and I can figure out how to best cater a solution to you. With this abstract example, it lacks the volume to be a good demonstration - what exactly would you expect `/:foo:bar` to match? When does the first segment stop, the second begin?

**Comment by thetutlage** [comment]
Okay lemme try to explain it again. Instead of sharing what I am already doing, lemme share what exactly I expect.

I want a RegExp, which matches the following use cases.

1. `/api/product/category`. **All static**.
2. `api/product/category/1`. Here `1` is a dynamic segment via `:id`. 
3. `api/product/category/1.json`. Here `.json` is a dynamic segment via `:format`. 

So the `/:id?:format?` will be optional.

I tried `/api/product/category/:id:format`. But it fails with the **number 1** use case.

**Comment by thetutlage** [comment]
Okay So if I try the same expression with [route tester](http://forbeslindesay.github.io/express-route-tester/) It generates the right regular expression.

But with `2.1.0` it generates a different one ( which is not working )

#### Express route tester output
- `/api/product/category/:id?:format?`
- `/^\/api\/product\/category(?:\/([^\\/]+?))?(?:([^\\/]+?))?(?:\/(?=$))?$/i`

#### With 2.1.0
- `/api/product/category/:id?:format?`
- `/^\/api\/product\/category\/((?:[^\/]+?))(?:((?:[^\/]+?)))?(?:\/(?=$))?$/i`


The difference is with route tester, the `/` after category is inside the optional block.

**Comment by blakeembrey** [comment]
@thetutlage Did you test your example at all from the route tester? If you did, you should see the same thing as I do and the same thing I said above - the RegExp doesn't make any sense and it doesn't work.

![image](https://user-images.githubusercontent.com/1088987/34892929-e9d336d2-f78f-11e7-8e91-0bbb4adcbfd8.png)

By providing a solid example of what you want, I can now tell you `/:id?.:format?` does everything you want to do and matches properly.

**Comment by thetutlage** [comment]
I believe you didn't saw the difference in the regex generated by the route tester and version `2.1.0`.

**Comment by blakeembrey** [comment]
I believe I did, and that's how it's worked since since 1.2.0 - three years ago.

![image](https://user-images.githubusercontent.com/1088987/34893954-444fe570-f794-11e7-8268-6e3750ce8f7c.png)

**Comment by thetutlage** [comment]
Okay then the route tester is not using the right version and thanks for the help.

**Comment by blakeembrey** [comment]
No, it's very out of date and should be updated - but the repo belongs to someone else. As for the specific feature, if you'd like to share a valid use-case it can be consider for re-support - it does look like it'd be hard to support properly though since the introduction of partial parameters in 1.3.0.

**Comment by thetutlage** [comment]
So the valid use case is that I accept a `format` as part of the URL and `format` is optional.

```
/posts:format(.json)?
/posts/:id/:format(.json)?
```

In above cases I want following URL's to work

```
/posts
/posts.json
/posts/1
/posts/1.json
```

Again not sure if this is not something to be supported by this library directly.

**Comment by blakeembrey** [comment]
It's not supported directly today because of how the "partial" behaviour works, but it could be added if it doesn't break any tests. Right now you'd need to use an array such as `['/posts.:format?', '/posts/:id.:format?']`.

**Comment by wesleytodd** [comment]
If you need to test with the route tester, use my fork.  It allows you to specify versions that are actually used in express.

https://wesleytodd.github.io/express-route-tester/
