### ISSUE TITLE
`/path/:id/edit*` not match with the path `/path/123/edit/basic`

### ISSUE THREAD

**Issue by WhatAKitty** [pillarjs/path-to-regexp#132]
So strange, the last time it worked.

At the same time, `/path/:id/edit/basic` matched with the patch `/path/123/edit/basic`

**Comment by agriffis** [comment]
Wouldn't you need a colon before edit? `/path/:id/:edit*`

**Comment by WhatAKitty** [comment]
@agriffis Why? `edit` is specific, and add a colon will match some wrong string like `/path/xxx/yyy/aaa` rather than `/path/xxx/edit/aaa`

**Comment by frenzzy** [comment]
What about this? `/path/:id/edit(.*)`

**Comment by agriffis** [comment]
@WhatAKitty Oh, I see. Does this do what you want? `/path/:id/edit/:foo*`

That should match on /path/123/edit and also /path/123/edit/basic because "basic" fills the zero-or-more `:foo` parameter, which you can ignore.

**Comment by WhatAKitty** [comment]
Thanks @agriffis and @frenzzy , `/path/:id/edit/:foo*` worked for me.

**Comment by blakeembrey** [comment]
Closing as answered. There's also a note in https://github.com/pillarjs/path-to-regexp#compatibility-with-express--4x.
