### ISSUE TITLE
path regexp do not work with hyphen

### ISSUE THREAD

**Issue by csvwolf** [pillarjs/path-to-regexp#134]
The path regexp is : `/:project([\\w\.\-@]+)`

But when the input is `test-1`, it don't work, while it will work in `test`.

Is there something wrong with my usage?

I use it in vue-router

**Comment by christophehurpeau** [comment]
Hello

It seems it's not the hyphen the problem but the number: perhaps you can add `0-9` like `/:project([\\w\.\-@0-9]+)` ?

**Comment by blakeembrey** [comment]
You need to use two backslashes like you did with `\\w`. Otherwise that mean `.-@`, probably not intentionally. For instance, `new RegExp('^[\\w\.\-@]+$').test('test/') //=> true`.

**Comment by csvwolf** [comment]
Yes, thank you all!
