### ISSUE TITLE
How to match all the strings except certain words?

### ISSUE THREAD

**Issue by eldeni** [pillarjs/path-to-regexp#138]
I may be making mistakes somewhere, while experimenting on 
https://pshrmn.github.io/route-tester/#/

but I wonder how are we supposed to write the path when we want to match all the possible strings except a few words. e.g. match `/foo`, `/bar`, but not `/baz` or `/quux`?

Tried with something like this `^(?!.*(baz|quux))` to no avail.
Anyone can help?

**Comment by blakeembrey** [comment]
I'd recommend using a regexp instead. Advanced expressions aren't supported today.
