### ISSUE TITLE
v2 broke react-router's "exact-allows-trailing-slash"

### ISSUE THREAD

**Issue by rjharmon** [pillarjs/path-to-regexp#140]
trying to update dependency from react-router from ^1.7.0.

Only one test fails - one that expects a path with trailing slash, with "exact" option set, to match a pattern that doesn't include trailing slash.

Including you for possibility that this behavior change may have been unintended.  See also https://github.com/ReactTraining/react-router/issues/5954

**Comment by blakeembrey** [comment]
This was a feature for 2.0 mentioned in https://github.com/pillarjs/path-to-regexp/blob/master/History.md#200--2017-08-23. There's also a bunch of duplicates reported back when 2.0 was released about this. It is intentional 😄
