### ISSUE TITLE
exclude based on specific value

### ISSUE THREAD

**Issue by nreoch25** [pillarjs/path-to-regexp#141]
Hello, I'd like to be able to match these routes:

/news/canada
/news/canada/toronto
/news/world

but then exclude the below:
/news/politics/morneau-budget-2018-pharmacare-1.4555186

Anything I try matches all of these routes and I can't find anything in the documentation for excluding a match based on a character.  For example. If there is a "-" or a "." in the path exclude from matching.

Thanks, any help is much appreciated
Nigel

**Comment by blakeembrey** [comment]
Use the custom matching groups for advanced matching. Something like `/news/:foo([^\-/])` could work.

**Comment by aryeharmon** [comment]
how can i exclude a specific word?

**Comment by blakeembrey** [comment]
You can write a regular expression for now.

**Comment by aryeharmon** [comment]
@blakeembrey i didn't exactly manage to make a regular expression like that. this is what i used:
/cms/:route0/:route1?/:route2(\b([a-z0-9]+)\b(?<!whatIWantToexclude))?/:route3?/:route4?/:route5?/:route6?/:route7?

**Comment by blakeembrey** [comment]
You need to use a regular expression for now, it's not possible using a string input.
