### ISSUE TITLE
Optional group with param compile

### ISSUE THREAD

**Issue by LKay** [pillarjs/path-to-regexp#142]
There are some issues: #95, #106 but I'm not sure if that is the same case.

I want to achieve something like optional group matching based on presence of a parameter and being able to compile path back.

I'd like to define a path like:
```
(/first/:one)?/second
```
And the first segment will be returned only if `:one` parameter is present:
```javascript
const toPath = pathToRegexp.compile("(/first/:one)?/second");

toPath(); // returns `/second`
toPath({ one : 1 }); // returns `/first/1/second`
```

Ideally I'd like to have some nested groups:

```javascript
const toPath = pathToRegexp.compile("(/first/:one(/second/:two)?)?/three");

toPath(); // returns `/three`
toPath({ two : 2 }); // returns `/three` because outer group "first" is not matched
toPath({ one : 1 }); // returns `/first/1/three`
toPath({ one : 1, two: 2 }); // returns `/first/1/second/2/three`
```

Is this even possible using this library?

**Comment by blakeembrey** [comment]
No, it's not possible like that. You can't embed params inside a matching group, it's a regexp expected inside there. It could be possible to consider this in future releases, but right now the only way to do it is to create two separate paths or use a regexp.

**Comment by blakeembrey** [comment]
Another idea would be to introduce nested groups that support paths instead of regexps and may solve a couple of other issues people are struggling with also. Something like:

```
{/first/:one{/second/:two}?}?/three
```

The parts inside `{}` are paths instead of regexps. To support this, however, we'd need to solve the same problem as https://github.com/pillarjs/path-to-regexp/issues/95 which will likely entail rewriting the parser to be an actual parser instead of regexps.

**Comment by LKay** [comment]
Fair enough, thanks for replying. 

Yeah, introducing `{}` for defining groups is a nice idea! 

First extract groups then perform usual regex conversion to whatever is inside `{}` and finally compile it all together by flattening extracted groups from the most nested one.

**Comment by delijah** [comment]
Actually with version 0.1.7 this worked. Check here: http://forbeslindesay.github.io/express-route-tester/

**Comment by blakeembrey** [comment]
@delijah I'm not sure anyone is arguing against that, but 0.1.x has a whole host of other bugs that resulted from being able to write paths like this.

**Comment by delijah** [comment]
Any progress on this?

**Comment by blakeembrey** [comment]
@delijah The best way to get progress on this is to submit a PR. I don't think the feature is particularly clear right now and it will need enough test coverage to ensure it works correctly.

**Comment by blakeembrey** [comment]
I tried implementing this, but one unclear feature is how `compile` works - from this path, how would we get a valid string back?

**Comment by Tofandel** [comment]
@blakeembrey For the path `(/first/:one)?/:second` this is the expected output
`{second: 'foo'} => /foo`
`{one: 'bar', second: 'foo'} => /first/bar/foo`

**Comment by blakeembrey** [comment]
@Tofandel That example is the really only the tip of the iceberg, what about `{/first/:one?}?` or other nested groupings? If `one` is missing`, does the child still get compiled? The proposal needs a solution for both parsing and compiling. If someone wants to put together such a proposal complete with edge cases, I can review implementing it.

**Comment by Tofandel** [comment]
`{/first/:one?}?` is equivalent to `(/first)?/:one?` so it would compile to this
`{second: 'foo'} => /first/foo`
`{one: 'bar', second: 'foo'} => /first/bar/foo`

Regarding nesting it would work as you'd expect

`(/first/:one(/nested/:nested))?/:second`
`{one: 'bar', second: 'foo'} => /foo //nested is required so doesn't match`
`{one: 'bar', nested: 'baz', second: 'foo'} => /first/bar/nested/baz/foo`

`(/first/:one(/nested/:nested)?)?/:second`
`{one: 'bar', second: 'foo'} => /first/bar/foo`

That's really all the edge cases there is

**Comment by blakeembrey** [comment]
Cool, feel free to submit a PR! Maybe some more will come up when you try implementing it, I recall running into issues when I actually tried to code it but that was also over two years back now.

**Comment by idler8** [comment]
```
const toPath1 = pathToRegexp.compile("/three");
const toPath2 = pathToRegexp.compile("/first/:one/three");
const toPath3 = pathToRegexp.compile("/first/:one/second/:two/three");

function toPathGroup() {
  const pathObject = { ...args };
  if (Object.hasOwnProperty("two")) return toPath3(pathObject);
  if (Object.hasOwnProperty("one")) return toPath2(pathObject);
  return toPath1(pathObject);
}
```
are you need `toPathGroup`?

**Comment by idler8** [comment]
> 

No, I don't need it

**Comment by blakeembrey** [comment]
V8 has implemented an optional path similar to the original proposal, but using `{}`. For example, `{/first/:one{/second/:two}}/three`.
