### ISSUE TITLE
Matching multiple paths with params

### ISSUE THREAD

**Issue by mreve** [pillarjs/path-to-regexp#145]
If I want my route to match for paths `/foo` and `/bar`, I can use a regexp `(/foo|/bar)` and it works.

However, if I'd need one of the paths to have a param (i.e. `/foo` and `/bar/:baz`), then the regexp `(/foo|/bar/:baz)` doesn't work (it matches for `/foo`, but it doesn't match for `/bar/:baz`).

**Comment by blakeembrey** [comment]
Duplicate of https://github.com/pillarjs/path-to-regexp/issues/142.
