### ISSUE TITLE
Shouldn't handle Function type param at branch 0.1.x

### ISSUE THREAD

**Issue by pflhm2005** [pillarjs/path-to-regexp#146]
As you write in the comments,path is {String|RegExp|Array},however,when I pass argument path with a Function type,it will be parsed as Sting type!Ultimately,the module return a useless regular expression.
So,I suggest that if the type of path is Function,directly return a empty String Regexp or throw error.

**Comment by blakeembrey** [comment]
I won't be making this change to `0.1.x` but would happily accept a good PR for `master`.

**Comment by pflhm2005** [comment]
I found another problem,how to handle Number?At present,it will always return an empty Regexp /^(?:\/)?$/i.I'm new to http and know path-to-regexp via express.js,if number type pathname is valid,it should be parsed as follows:
`return stringToRegexp(/** @type {Number} */ String(path), keys, options)`
or,throw an error.

**Comment by blakeembrey** [comment]
JavaScript isn’t strongly typed for arguments and trying to handle every possible argument is expensive. I’d prefer to just add type checks to the applicable functions for the applicable types.

**Comment by pflhm2005** [comment]
It's my first time that I post a PR just now.
Unfortunately, code coverage couldn't reach 100%, 'throw new TypeError' statement can't be covered.
Maybe there is something wrong with my code.
Help...

**Comment by blakeembrey** [comment]
I'm going to close this issue. The library doesn't do any type checking internally. If you want stronger types, you'll need to look into something like TypeScript.

**Comment by pflhm2005** [comment]
fine,thanks.
