### ISSUE TITLE
Keys doesn't get populated in the simplest example

### ISSUE THREAD

**Issue by funkjunky** [pillarjs/path-to-regexp#151]
```javascript
import pathToRegexp from 'path-to-regexp';

var re = pathToRegexp('/foo/:bar', keys)
// re is /^\/foo\/([^\/]+?)\/?$/i
// keys is undefined
```

**Comment by dougwilson** [comment]
> keys An array to be populated with the keys found in the path.

Updates your example to pass that array in this time :+1:

```
import pathToRegexp from 'path-to-regexp';

var keys = []
var re = pathToRegexp('/foo/:bar', keys)

console.dir(keys)
```

**Comment by blakeembrey** [comment]
Thanks @dougwilson 👍 

@funkjunky, you need to define `keys` as an array before you pass it into the function. If it's `undefined` there's nothing to populate. Feel free to submit a PR if the documentation is unclear.
