### ISSUE TITLE
What is the support for regex?

### ISSUE THREAD

**Issue by Martinsos** [pillarjs/path-to-regexp#152]
Hi!
First of all, thank you for this cool library :)!

I was looking at docs and I understand there are custom rules for defining a path (like using `/:tokenName` to catch that part of url) and that there is also some support for regex, however what I could not completely understand is where and in which extent is regex supported?
E.g. I tried specifying route as `/app/dataset(?:/.*)` to catch both `/app/dataset` and `/app/dataset/123` however that did not work.
Since there are custom rules, the whole string is obviously not parsed as a regex, so what is parsed as a regex? Only certain parts? Does it have to be in the parentheses? It would be great to understand this better! Thanks

**Comment by frenzzy** [comment]
If you want to use regex, you need to pass [RegExp](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) instance: `/^\/app\/dataset/`
Instead of just a string: `/app/dataset/:any?`

**Comment by Martinsos** [comment]
But even if I pass a string, there is some support for regexes inside it, from what I see in the docs, and I would like to understand that support better.
Btw. I am using path-to-regexp through react-router-dom and there I can pass only string, not RegExp.

**Comment by blakeembrey** [comment]
The parts inside the parentheses (under custom match parameters in README). The regexp you say you tried wouldn’t be correct in any case because the parentheses group needs to be optional. This library does not support non matching groups like you’ve tried to define either, only custom matching groups that override the default behaviour.
