### ISSUE TITLE
How can I get compile to keep my trailing slash when using a wildcard param?

### ISSUE THREAD

**Issue by timwis** [pillarjs/path-to-regexp#155]
I'm working on a piece of server middleware to handle redirects and rewrites. I've got it mostly working, but I'm running into an issue supporting rewrites: path-to-regexp seems to remove the trailing slash when I use `.compile()` with a wildcard parameter, if no value is specified for that parameter. To illustrate:

```javascript
// With wildcard
const toPathWith = pathToRegexp.compile('https://cityofphiladelphia.github.io/zoning-appeals/:any*')
console.log(toPathWith({}))
//=> "https://cityofphiladelphia.github.io/zoning-appeals"

// Without wildcard
const toPathWithout = pathToRegexp.compile('https://cityofphiladelphia.github.io/zoning-appeals/')
console.log(toPathWithout({}))
//=> "https://cityofphiladelphia.github.io/zoning-appeals/"
```

The problem is that I do need to support the wildcard so it will work for things like `/css/styles.css` but also for the root (`/`). When path-to-regexp maps it to a URL without a trailing slash, the underlying server I'm rewriting (github pages) responds with a 301 redirect to the address _with_ the trailing slash.

I understand why path-to-regxp makes the trailing slash optional. But how would I go about getting `.compile()` to include it in this scenario?

**Comment by blakeembrey** [comment]
So I can't be 100% sure of what you're trying to do, but the `/` is considered a prefix. Basically needs 1 or more segments to show up. Given this, what about `pathToRegexp.compile('https://cityofphiladelphia.github.io/zoning-appeals/:any*/')` (using a trailing slash)? Feel free to include more information if I'm off track here.

**Comment by blakeembrey** [comment]
FWIW, matching should exhibit the same way - it's just trailing slashes are optional by default unless you enable `strict`. Maybe that's something else you may be interested in?

**Comment by timwis** [comment]
The trailing slash on compile with `/:any*/` did it. Thanks!

**Comment by timwis** [comment]
Ah, just realised that has a side-effect of also rewriting image requests to `/zoning-appeals/foo.png/` :(

For context, I'm trying to parse this list of rules into a request handler that performs redirects and rewrites:

```
/otis                     301 http://www.phillyotis.com
/parksandrec/:any*        301 /departments/philadelphia-parks-recreation/
/revenue/:any*            301 /departments/department-of-revenue/:any*
/li/zoning-appeals/:any*  200 https://cityofphiladelphia.github.io/zoning-appeals/:any*
/contracts/data/:any*     200 https://cityofphiladelphia.github.io/contracts/:any*
/httpbin/:any*            200 https://httpbin.org/anything/:any*
```

It works if I add a rule for:

```
/li/zoning-appeals/       200 https://cityofphiladelphia.github.io/zoning-appeals/
```

But then I end up needing 3 rules for that 1 site:

```
/li/zoning-appeals        301 /li/zoning-appeals/
/li/zoning-appeals/       200 https://cityofphiladelphia.github.io/zoning-appeals/
/li/zoning-appeals/:any*  200 https://cityofphiladelphia.github.io/zoning-appeals/:any*
```

Does that make more sense?

**Comment by blakeembrey** [comment]
One possibility is using `strict` and then adding two rules - one with and one without the trailing slash. Aside from that, we'd need to add some functionality into `path-to-regexp` to support optional trailing slash matching and copying - maybe it's a matter of changing `[^/]+` into `[^/]*` so empty values could consider the prefix. I imagine this would have negative side effects without testing it though. Feel free to make a suggestion of how you see this could be handled better.

Another idea is using an optional group to capture the trailing slash (with `strict` mode enabled, e.g. `(/)?`).

**Comment by blakeembrey** [comment]
The best solution in this scenario would be to adopt `/:any(.*)` and forward it verbatim.
