### ISSUE TITLE
Optional path as variable

### ISSUE THREAD

**Issue by jag1989** [pillarjs/path-to-regexp#156]
I'm using a [VueRouter](https://router.vuejs.org/), which uses the path-to-regexp library. I'm trying to create an optional path, which can also be anything and stored as a variable. 

```
import Vue from 'vue';
import Router from 'vue-router';
import LandingPage from './views/LandingPage.vue';
import DetailsPage from './views/DetailsPage.vue';
Vue.use(Router);

export default new Router({
	mode: 'history',
	routes: [{
		path: '/:campaign?',
		name: 'home',
		component: LandingPage
	},
	{
		path: '/(:campaign/)?your-details'
		name: 'your-details',
		component: DetailsPage
	}]
});
```

The home (/) route works fine/as expected being able to go to any of the following

- `/`
- `/foo`
- `/bar`

The your-details route only works when visiting `/your-details` however I want to to work with 

- `/your-details`
- `/foo/your-details`
- `/bar/your-details`

Is this possible?

**Comment by blakeembrey** [comment]
Per the README (https://github.com/pillarjs/path-to-regexp#custom-matching-parameters), everything inside `()` is a regexp which would explain why you can't get it to match. Have you tried doing `/:campaign?/your-details`?
