### ISSUE TITLE
The Parameters of the keys is  Unnamed When path is a regular expression , I don't know  which situation it will be used

### ISSUE THREAD

**Issue by gaollard** [pillarjs/path-to-regexp#157]
```
/**
 * Pull out keys from a regexp.
 * @param  {!RegExp} path
 * @param  {Array=}  keys
 * @return {!RegExp}
 */
function regexpToRegexp (path, keys) {

  if (!keys) return path
    
  // Use a negative lookahead to match only capturing groups
  var groups = path.source.match(/\((?!\?)/g)
  if (groups) {
    for (var i = 0; i < groups.length; i++) {
      keys.push({
        name: i,
        prefix: null,
        delimiter: null,
        optional: false,
        repeat: false,
        partial: false,
        pattern: null
      })
    }
  }

  return path
}
```

I can't understant in [unnamed-parameters](https://github.com/pillarjs/path-to-regexp#unnamed-)parameters

I will be great of appreciation If somebody help with my confusion.

**Comment by blakeembrey** [comment]
I'm not sure what your question is, but unnamed means it has no name. They become just a number. For example, `/(\d+)` will result in key names `[0]`. In the case of a regexp, the same applies. It matches any matching groups from the regexp source and applies numeric key names so it doesn't mess up with indexing of matched results.

**Comment by gaollard** [comment]
@blakeembrey thanks for your answer
