### ISSUE TITLE
Exclude value from URL

### ISSUE THREAD

**Issue by Puuuudding** [pillarjs/path-to-regexp#158]
issue: #141 

Currently I'm in a similar situation as this closed issue. I have following URLs to be matched:

/customers/statistics
/customers/profile/:id
/customers/segments/:id
/customers/setting/segments/:id

I want to exclude the last one (setting). When using standard regular expression I would write
`/\/customers\/(?!setting)`
to test these URLs. But when I use this expression in path-to-regexp, I find that the exclamation mark will be escaped by the tool which leads to the result
`/^\/customers\/(?\!setting)(?:\/)?$/`
which will cause regular expression parse error in JS.

Do you have suggestion to solve this issue? I am on version 2.2.1

Thank you!

**Comment by blakeembrey** [comment]
It looks like you used a string, not a regular expression. Regular expressions are not changed in any way.
