### ISSUE TITLE
[IDEA] Add support for RegExp named capture groups

### ISSUE THREAD

**Issue by HelloEdit** [pillarjs/path-to-regexp#159]
Hi,

NodeJS 10 came out with a considerable number of new features. One of them is the RegExp named capture groups, which allows you to capture all the data you need.

```js
const RE_DATE = /(?<year>[0-9]{4})-(?<month>[0-9]{2})-(?<day>[0-9]{2})/;

const matchObj = RE_DATE.exec('1999-12-31');
const year = matchObj.groups.year; // 1999
const month = matchObj.groups.month; // 12
const day = matchObj.groups.day; // 31
```

[Proposal here](http://2ality.com/2017/05/regexp-named-capture-groups.html)

I think it would be super useful to introduce an option only for node >= 10 allowing `path-to-regexp
` to have this functionality. I am not yet interested in the code of this package to be able to propose a PR. I'll look at it later.

Thanks for your work,

**Comment by blakeembrey** [comment]
Please describe what you want to do. You haven't provided any reason it would be super useful. If you can't figure out your issue without named groups, how would it possibly work with named groups?

**Comment by HelloEdit** [comment]
I see it that way:

When the path is transformed into regex, the output regex will have the capture groups in the name of the different parameters provided to the pathToRegexp function.  This will execute the regex on a string and get the name of each group directly in the result of the regex.  I don't know if you agree with this vision but I find it more productive than an array.

Then, and this is a much more personal situation, I'd like to know what argument the Regex didn't parse correctly. only the.compile returns a TypeError and I'm in full search to know how to have this behavior as simply as possible.  I don't think it's connected to that issue.

**Comment by blakeembrey** [comment]
I think what I need from you is for you to describe the problem you are facing clearer. I understand what you'd like to see, but fail to see how it would solve your problem. The feature mentioned in https://github.com/pillarjs/path-to-regexp/issues/153 would be equivalent to providing the "groups" output, but it'd have the advantage of being a function controlled by `path-to-regexp` so it can do things like decode values and define an API other path matching libraries can also replicate. Not to mention it'd work the same for all node.js versions.

The issue you mention sounds like you're using [`compile`](https://github.com/pillarjs/path-to-regexp#compile-reverse-path-to-regexp)? Your suggestion would not change anything in that part of the library.

**Comment by HelloEdit** [comment]
Hi,

For my situation, I use this package in a hijacked way to analyze a string with arguments. However, the regex produced by path-to-regexp, or even any function of the package, does not tell me where the error is (the regex condition that is not met) in the analysis of this string.  I would like to know, as using compile, the TypeError.  Using named groups would allow me to manually check which arguments are present and which are not, allowing me to generate the TypeError myself. Maybe there is a simpler way to do this, in which case I didn't find it.

**Comment by blakeembrey** [comment]
I really don’t think named groups would help you at all. If you’re using compile, that’s in the reverse direction and you wouldn’t be able to use a regexp to check an object anyway. If your issue is just that, we can just attach a property to the thrown error so you know exactly what failed.

**Comment by HelloEdit** [comment]
it seems good to me, even if the integration of the named group would be a plus, I agree with your point of view.

**Comment by alber70g** [comment]
Any chance this will be implemented at some time? For us we use path-to-regexp to store route configuration, and later retrieve this and use it in the client. It would eleminate the use of the pattern completely when we can just use the capture groups.

**Comment by blakeembrey** [comment]
@alber70g I'm working on this today.

For future reference, as an OSS project you can always submit a PR. It's a lot more effective at getting the ball rolling than prodding maintainers. Consistent prodding typically leads to burnout, which is why I largely dropped off open source for the past few years.

**Comment by blakeembrey** [comment]
Implemented in https://github.com/pillarjs/path-to-regexp/commit/0e0dce99b91b3deba85c2b5e97b161762a13c5d9.
