### ISSUE TITLE
Support for enumeration matching

### ISSUE THREAD

**Issue by vijayst** [pillarjs/path-to-regexp#161]
Is there any support for enumeration matching.

/red
/green
/blue

/:color route should match only if it is one of the above routes. Any regex for this?

Asked a similar [SO question](https://stackoverflow.com/questions/51879488/match-a-route-only-if-a-route-param-matches-an-enumeration-value).

**Comment by frenzzy** [comment]
`/:color(red|blue|green)`

**Comment by vijayst** [comment]
Perfect, thanks.

**Comment by matteoferigo** [comment]
It seems not to work as aspected.
The forumula `/:lang(en|es)` matches both `/en` `/es` and even `/english` `/entrace` `/escape`
How is it possible to limit the length of the variable?
