### ISSUE TITLE
[Bug] Behaves incorrectly when option `strict` is set to `false`

### ISSUE THREAD

**Issue by somombo** [pillarjs/path-to-regexp#162]
```js
const assert = require('assert')
const ptr = require('path-to-regexp')

const re =  ptr("/foo/", {
    strict: false
})

assert( re.test("/foo") /* <-- should return `true` if option strict is false */ )
```

I tested the above on versions:
- 0.1.7 (✔️ works)
- 1.7.0 (✔️works)
- 2.0.0 (❌ fails)
- **latest 2.2.1 (❌fails)**

I have also noticed that the test suite does not cover any test case where Option `strict`  is `false`. There was too much in the one `test.ts` file  to get my head around, so I was unable to contribute a PR with this test case. Perhaps someone can assist with that?

**Comment by somombo** [comment]
Not an expert of regex, but I think the output of `console.log(re)` in the above snippet, is supposed to be
`/^\/foo(?:\/)?$/i`  and not `/^\/foo\/(?:\/)?$/i` as is currently the case in v2.2.1

I determined this by analogously extrapolating the output v1.7.0

Hopefully that helps fix something

**Comment by blakeembrey** [comment]
No, this is expected behaviour and is documented in the changelog. It is also tested in the test suite. That’s generally what a major version indicates - a breaking change.

**Comment by somombo** [comment]
sorry, I expected the changelog to be at https://github.com/pillarjs/path-to-regexp/releases, like every other repo.

Also, if this feature was removed/changed/broken in v2.0.0 why it still documented as: 

> **strict:** When false the trailing slash is optional

still noted on your **main** documentation. it's obvious. you know.. the place that is the first obvious place where someone looks if they are trying to figure out how to use this in a consistent manner..

Can you kindly update the main documentation to reflect what exactly that option is now for (or if it even still an option).

I have now read the `history.md` you are referring to as changelog, however it is still not clear to me what `strict` does or how it is supposed to behave.. and I will say the way it is currently documented is consistent with (understandable as) the way it worked before.

Thanks

**Comment by blakeembrey** [comment]
The option works the same way, it allows an optional trailing slash on the input. You’re welcome to submit a PR to clarify the documentation.

**Comment by somombo** [comment]
I'll be glad to PR the documentation once I understand ... But I'm still lost.

> The option works the same way

Works the same way as what? Certainly not the same way as it did before, otherwise the test snippet I provided above wouldn't fail.

> it allows an optional trailing slash on the input

If it allows an optional trailing slash, why does input of `/foo` fail when `path` is defined as `/foo/`  (as I showed in the test above?

Am I missing something?

Isn't the second of these slashes (the one at the end of `/foo/` ) what you are referring to as the "trailing slash"? Well, my test should pass if that last slash is not provided (as in `/foo`) seeing as you say it is "optional".

Please clarify

**Comment by blakeembrey** [comment]
It’s optional on the string you are matching to regular expression. It doesn’t make much sense to strip characters you wrote from the path argument as v1 did.

**Comment by somombo** [comment]
> It’s optional on the string you are matching to regular expression

to me this ☝️  still means 👇 

```js
re.test("/foo") // <-- should yield `true`
```

(Since `re` is the regex, `"/foo"` is the "string" and `test` is the matcher)

Could you maybe provide a code snippet showing what this option is used for. when to use it and when not to use it, Or equivalent/analogous input for some path, that you wouldn't be able to provide unless string was turned on/off?

I'm really having a hard time here.

**Comment by blakeembrey** [comment]
Just don’t write the path with a trailing slash if you expect the trailing slash to be optional. By writing it in the string you’re effectively saying it should be there. It’s confusing that you wrote a trailing slash and expect it to match paths without a trailing slash. Why can’t you just write it without a trailing slash to start with?

**Comment by somombo** [comment]
>  It’s confusing

Obviously this wasn't confusing to many users for so many versions of the library, otherwise it would have been removed alot earlier.

what's confusing or not confusing is obviously a subjective matter, that I'm personally not concerned with. I'm only concerned with figuring out how exactly this feature currently works, (i.e. "What does `strict` do?") ... 
I think I have asked a simple question in as black & white a way as possible. Even asked for a code snippet example...

Therefore, you prescribing 

> Why can’t you just write it without a trailing slash to start with?

Because you think it's confusing, is frankly patronizing and doesn't answer my black/white question.

All you had to say was, in summary:

> Option `strict` only does something when the defined path does not already have a trailing slash. 

That's now understood. 

This may seem obvious to you, but it's not to me and I suspect others as well. Again I am not asking for a change to the subjective decision of why this works like that, only wanted to understand *what* it currently does ... period.

If you should feel so inclined, you can add something like the following to your documentation:
> **strict:** When `false` the trailing slash is optional. This only works when the defined path does not already have a trailing slash.

I have no further questions or comments. Thank you
