### ISSUE TITLE
Help with path

### ISSUE THREAD

**Issue by TheoneLucas** [pillarjs/path-to-regexp#167]
Hi, I've been trying to make a given path but after a lot of reading I started wondering if this specific path is even possible with the library. The path would look something like this:

```
/:domain/category?/:categories*?/f?/:filters*
```

Where:

| Segment | Description |
| ------ | ------ |
| `:domain` | Variable string (a parameter) |
| `category?` | An optional segment (Don't know if possible, it should either be `category` or won't be present) |
| `:categories*?` | An optional parameter that has 0 or more, it will be present if the previous segment (`category?`) is present |
| `f?` | An optional segment (Same as `category?`), it either will be `f` or won't be present |
| `:filters*?` | Same as `:categories*?`, but respective to `f?`. An optional parameter that has 0 or more, it will be present if the previous segment (`:filters*?`) is present |

I've build the following path:

```
/:domain/:categoria/:categories*/f/:filters*
```

Which somewhat works, only when all segments are present, like in this URL:

```
/domain/category/category1/category2/category3/f/filter1/filter2/filter3
```

Which returns me the following segments:

```
category: "category"
categories: "category1/category2/category3"
domain: "domain"
filters: "filter1/filter2/filter3"
```

All that seems fine, but I need to make both `categories` and `filters` optional, so the following URL's would match the path:

```
/domain/category/category1/category2/category3
/domain
```

Is that possible? Thanks!

**Comment by wesleytodd** [comment]
I think this answer depends on which version of this you are using, but you can do something like `/category/:category*/(filter?)/:filter*`.  Then you would need to split out the category and filters after you get that `req.params.category && req.params.category.split('/')`.  

Does something like that work for you?

**Comment by nhpolanco** [comment]
@wesleytodd this doesn't work as expect. at least testing against the version of `path-to-regexp` included in react router v4 (^1.7.0, I believe). I've been using this handy tool to test potential : https://pshrmn.github.io/route-tester/#/

I cant seem to find a path definition that combines an optional named prop + optional named group of props + an optional static prop + another optional named prop group in that order. The only limitation should be anything before the static optional prop should be grouped, and everything after the static prop should be group - no matter the number of props

To illustrate, I need something that matches both `/base/category1/category2/category3/s/feature1/feature2` and `/base/category1/category2/category3/category4/s/feature1/feature2/feature3` ; without limiting the number of categories or features, and having the path separator `/s/` be optional - in fact have everything but the base be optional

might not be an issue, but any help is welcome.

**Comment by wesleytodd** [comment]
Hey @nhpolanco, I see what you mean that the `filter` part is fully optional.  I would probably recommend having two routes which use the same handler, one with the filter and one without.  I do not us react router, so cannot advise on how to set that up with it, but in express this would look like the following:

```
app.get('/base/:category*/filter/:filter*', handler)
app.get('/base/:category*', handler)
```

If it failed to match the first route, it would just fall through to the second, but both use `handler`, so your code would just have to check for the existence of `req.params.caregory` and `req.params.filter`.  Does that help?

**Comment by nhpolanco** [comment]
@wesleytodd great, that seems to work. just for clarity, there is no way to define `/filter/` (static filter separator) as an optional in a single path, and encapsulate those two routes into one?

**Comment by blakeembrey** [comment]
It’s not entirely possible with regexps because, if all segments are entirely optional, it would be valid to match the entire path as just “category”. Making it work would also cause regexp backtracking and confusion with a path like `/filter/filter/filter/filter`. I’d be happy for someone to take a stab at it, but just using an array of paths would be the preferred approach today.

**Comment by nhpolanco** [comment]
for posterity, i found a way to capture multiple optional groups in a single path-to-regex path like so: 

`/:base/:route(.*?)?/(q?)/:categories(.*)?`

**Comment by blakeembrey** [comment]
@nhpolanco Makes sense. That should mostly be the same as `/:route*/(q)?/:categories*` also.
