### ISSUE TITLE
Reverse PathToRegex

### ISSUE THREAD

**Issue by jamalabo1** [pillarjs/path-to-regexp#169]
Hello,

is there any one to reverse the way the path-to-regex working? 

### example
 
```
var re = fx('/product/:id', '/product/123');

// return true if matched
```

is there anyway to do that?

**Comment by blakeembrey** [comment]
I'm not quite sure I understand your question, but your example is how `path-to-regexp` works. There's an example in https://github.com/pillarjs/path-to-regexp#named-parameters. If you want `true` or `false, use `re.test` instead of `exec`.
