### ISSUE TITLE
Support empty strings in compile

### ISSUE THREAD

**Issue by rat9988** [pillarjs/path-to-regexp#170]
Hello,

I have a usecase where I want to accept empty strings in the compile functions. Unfortunately, it did throw an error because of this line of code (line number 178)

```
if (!matches[i].test(segment)) {
   throw new TypeError('Expected "' + token.name + '" to match "' + token.pattern + '", but got "' + segment + '"')
  }
```
To solve it, I changed line 178 to : 
`if (segment!="" && !matches[i].test(segment))`

A better way might probably have been to change the RegExp, but it makes it less readable in my opinion.

Is it possible to incorporate such a change in the library? Or maybe there is a rationale to why you don't want to support such a usecase?

(I'm new to github, sorry if I didn't respect the rules)

**Comment by blakeembrey** [comment]
@rat9988 Because it would produce a URL that's invalid according to the matching rules. It's not valid to have a URL that does `/:path/something` and match `//something`. You should either use an optional param, or write a custom matching regexp in the string.

**Comment by OliverJAsh** [comment]
I would like to second this. I don't like the fact that the function may error at runtime without any error at compile time.

I am using TypeScript and I've defined the type of my params, e.g.

``` ts
type Params = { query: string; };
const pathPattern = '/search/:query';
```

When I generate a path using this pattern, I get a compile time type error if I pass no query. However, I don't get a type error if I pass an empty query. I only get a runtime type error, which means I don't discover the problem until the code is already in production.

``` ts
const toPath = pathToRegexp.compile<Params>(pathPattern);
toPath({}) // compile time type error
toPath({ query: 'foo' }) // fine
toPath({ query: '' }) // runtime type error
```

Perhaps we could add an option to disable exceptions for empty strings?

**Comment by blakeembrey** [comment]
@OliverJAsh I definitely understand it's a bummer. My largest concern here is really just generating a path that wouldn't be matched if it were to be used as the URL. I can definitely add a flag that disabled validation, but it wouldn't be recommended or default. How does that sound? What's the use-case that an invalid URL should be possible to generate?

**Comment by OliverJAsh** [comment]
> What's the use-case that an invalid URL should be possible to generate?

So far I've found two:

- Our API had a bug where it returned empty strings (which we then used to create URLs).
- We have some mock data for our tests where we used empty strings because the particular values didn't matter, as long as it was a `string`.



> My largest concern here is really just generating a path that wouldn't be matched if it were to be used as the URL

Hmm, I see.

Another option is returning `undefined` if the params aren't "valid" (i.e. empty strings for required params). I understand that would be a breaking change though.

**Comment by OliverJAsh** [comment]
> > What's the use-case that an invalid URL should be possible to generate?

Another place where this just happened: we were generating a URL from a query parameter. In Express these can be empty strings, e.g. for `/?foo=`, `req.query.foo` would be `''`.

**Comment by mattfysh** [comment]
My use case is also around empty strings in the ?query section. I ended up using a proxy:

```
new Proxy(data, {
    get: (target, prop) => target[prop] || '',
  })
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy

**Comment by mattfysh** [comment]
Actually nope, that don't do it... still causes an error to be thrown.

I also noticed an error was being thrown when the first character is a `#`, even though an `encode` parameter was being provided, which seems like a bug. You should be testing the pattern against the segment **after** encoding
