### ISSUE TITLE
Not clear from docs how to generate a regexp from a path syntax.

### ISSUE THREAD

**Issue by papiro** [pillarjs/path-to-regexp#171]
I thought that path-to-regexp generated a regexp from a path syntax for you, but I am having unexpected results. 

Example:
```
const re = pathToRegexp('*/assets');
const foo = re.exec("foo/assets");
// null
```
I would expect this to output a match of some sort. Copying and pasting examples aren't helping either. From the docs:
```
var re = pathToRegexp('/foo/*', keys)
// keys = [{ name: '0', ... }]

re.exec('/foo/bar/baz')
//=> ['/foo/bar/baz', 'bar/baz']
```
I get null when I copy and paste this code, with the caveat that I'm running it both with the `keys` param removed (since it's unclear to me how `keys` is supposed to work), and with `const keys = [{ name: '0', delimiter: '/', optional: false, repeat: true }]` which I just copied from the last example in the docs before this one which didn't have an ellipse summarizing the rest of the object comprising `keys`... From the docs, it seems keys should be an empty array which I pass and which path-to-regexp will populate, but when I pass an empty array, it's still an empty array after invocation.

Using version 2.4.0

Update while forming my question: I just tried the above examples on version 1.7.0 and they produced the output expected. So confusing!

**Comment by blakeembrey** [comment]
That’s probably because you’re reading docs from 1.x but using a different version. If you read the documentation on GitHub or for your version, you shouldn’t see that notation anymore.

**Comment by papiro** [comment]
I was reading the docs on the landing page (README) of the repo, which is 2.4.0.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dougwilson** [comment]
I don't see `pathToRegexp('/foo/*', keys)` anywhere on the 2.4.0 readme. Where on the readme did you get that from? It's not valid syntax in 2.4.0 which is why you get no match, which is expected. It would not be expected to be in the 2.4.0 readme, though.

For reference I'm using the readme I believe you described: https://github.com/pillarjs/path-to-regexp

**Comment by papiro** [comment]
Oh dear... what have I done. I see the "Asterisk" section actually missing entirely from the docs on 2.4.0... Turns out the only thing confusing here is me. I was mistaken - sorry about this!
