### ISSUE TITLE
Route breaks in latest, but works in v2.0.0

### ISSUE THREAD

**Issue by pizza-r0b** [pillarjs/path-to-regexp#172]
The following works in v2.0.0 but breaks in v2.4.0

Here's the error in 2.4.0
```js
pathToRegexp('/(login)?');

Invalid regular expression: /^\/(?(?:([^\/]+?)))?\/?$/: Invalid group
```

**Comment by blakeembrey** [comment]
@pizza-r0b I'm unable to replicate this issue, I even added a test case for you.

**Comment by blakeembrey** [comment]
![image](https://user-images.githubusercontent.com/1088987/49332387-2ec38b00-f561-11e8-8053-8f3d7ee197a4.png)

**Comment by pizza-r0b** [comment]
Weird. Definitely was seeing it. When I required via node cli it worked, but when I bundled with webpack it gave me the same error that can be seen using http://forbeslindesay.github.io/express-route-tester/ and specifying version 0.1.7. Thanks

**Comment by dougwilson** [comment]
0.1.7 is the version Express 4.x uses. It sounds like perhaps there is some config such that during your webpack, it tries to collapse into only one version of path-to-regexp and so you can't use two versions at the same time. Just a thought.
