### ISSUE TITLE
Match only routes with less than 5 characters

### ISSUE THREAD

**Issue by jimmiebtlr** [pillarjs/path-to-regexp#181]
I'm trying to use 
```
^.{3,4,5}$
```

To match all routes where 3-5 characters are available, but not longer.  $ get's escaped though and I can't figure out how to unescape that.

**Comment by jimmiebtlr** [comment]
One other note is that I'm using https://github.com/fridays/next-routes

Which I think pretty much only exposes the "patterns" var from path-to-regexp.

**Comment by blakeembrey** [comment]
@jimmiebtlr That doesn't match the use-cases in the README. You'd either have to use a RegEx directly, or make it a param like `(.{3,5})`.
