### ISSUE TITLE
Custom regex does not match

### ISSUE THREAD

**Issue by AntoniosProvidakis** [pillarjs/path-to-regexp#184]
I'm testing a custom regex on your [demo site](http://forbeslindesay.github.io/express-route-tester/).

Package Version: 0.1.7
- [ ] Strict
- [ ] Sensitive
- [x] End

In the route field I type: _/person/:id([1-9]\d*)_.
I am expecting the "id" param to be a positive integer (excluding zero).

In the path input I type: _/person/1_,
but I get the message "The path does not match the route".

All one-digit (1-9) ids do not match. id only matches when it starts being two-digit, i.e. 10, 11, 12, 13, etc.,

Also, id with a leading zero (e.g. 015) does not match, which is well-expected.

Why do single digit ids not match?
Am I missing something here?

**Comment by AntoniosProvidakis** [comment]
@blakeembrey Any chance you could help?

**Comment by blakeembrey** [comment]
It’s because an asterisk in 0.1 expands into a wildcard. This is a historical unfixable bug. Avoid using the asterisk and you’ll be fine.

**Comment by AntoniosProvidakis** [comment]
@blakeembrey  So, something like: **/person/:id([1-9]\d{0,})** would be equivalent, right?

**Comment by blakeembrey** [comment]
Yes.

**Comment by AntoniosProvidakis** [comment]
@blakeembrey  Thank you so much.
I'll close this issue.
