### ISSUE TITLE
remove last slash from segment

### ISSUE THREAD

**Issue by avilaj** [pillarjs/path-to-regexp#186]
hi, i'm using version 2.

i have the following path

`/:slug(.*/)?:keyword?`
and i want the followin url 
`/slug1/slug2/keyword-test`

to produce
```
slug: slug1/slug2
keyword: keyword-test
```
but slug is adding a slash
`slug: slug1/slug2/`

How should i configure my route to ignore that last slash on slug?

**Comment by paulmelnikow** [comment]
It's doing that because your pattern for slug includes the slash.

I'd suggest using this: `/:slug?/keyword?`

**Comment by blakeembrey** [comment]
@avilaj I'm going to close this issue, the suggestion by @paulmelnikow + README information should help clarify what's happening. E.g. `/:slug*/:keyword?` would work, though having repeated optional parameters doesn't always make a lot of sense.
