### ISSUE TITLE
Custom regexep parameters are escaped when provided as string.

### ISSUE THREAD

**Issue by FabianSellmann** [pillarjs/path-to-regexp#189]
Hi, I am using path-ro-regexp through react-router.

According to the docs:
 
>All parameters can have a custom regexp, which overrides the default match ([^/]+). For example, you can match digits or names in a path.

However when providing a path as a string as such:
`test/:page((?!foo))` it creates this kind of regexp
`/^\/test\/(((?:?\!foo))\)(?:\/(?=$))?(?=\/|$)/` - One would expect that the part of the custom regex in the parenthesis would not get escaped in the string. 

Would there be a way to provide custom params regexp with a negative lookahead in a string?

If the string has been changed by react-route, I apologize and this issue could just be closed.

**Comment by blakeembrey** [comment]
There currently isn’t any support for negative lookaheads in the custom RegExp.

**Comment by FabianSellmann** [comment]
Thank for clarifying this.
