### ISSUE TITLE
Match pattern

### ISSUE THREAD

**Issue by abumusamq** [pillarjs/path-to-regexp#192]
Is it possible to match something like this? `/user/(profile|settings)/:user_id`.

Version < 1.0 doesn't support it and express uses version 0.x (creates invalid regexp)

**Comment by blakeembrey** [comment]
I assume you're asking specifically in 0.x which is currently an unsupported version. I'd recommend trying in http://forbeslindesay.github.io/express-route-tester/, but if you just name the second param it'll work in 0.x - `/user/:foo(profile|settings)/:user_id`.
