### ISSUE TITLE
Typescript doesn't export a pathToRegexp function.

### ISSUE THREAD

**Issue by burtonator** [pillarjs/path-to-regexp#193]
I think your TS bindings are wrong...

You export a namespace named pathToRegexp but not a function.

Which means from inside TS that's not callable.

this makes the entire module not usable as TS for the most part.

**Comment by burtonator** [comment]
Do fix this you probably need to define a new function named pathToRegexp and probably create a PathToRegexp namespace.

**Comment by blakeembrey** [comment]
The TypeScript binding is correct, you're probably using it wrong.

**Comment by hacknlove** [comment]
@burtonator This is working for me

```js
import * as pathToRegexp from 'path-to-regexp'
pathToRegexp.pathToRegexp(path)
```
