### ISSUE TITLE
Allow double slash in regExp.

### ISSUE THREAD

**Issue by bram-ontoforce** [pillarjs/path-to-regexp#194]
When creating a regular expression with the plus sign

```javascript 
const regexp = pathToRegexp('/foo/:bar+')
```

it will match everything after /foo/

```javascript 
regexp.exec('/foo/test1/test2') // test1/test2
```

but the match stops as soon there is a double slash

```javascript 
regexp.exec('/foo/test1//test2') // test1
```

**Comment by blakeembrey** [comment]
@bram-ontoforce I'm not entirely convinced this is a good idea. Why do you want to do this?

**Comment by maranomynet** [comment]
I came here to report this same issue.

@blakeembrey I understand your concern, but would it not be possible to somehow solve this for arbitrary number of adjacent slashes by accepting zero or more characters (i.e. the empty string) between slashes when matching these repeat tokens?

...or would that open some other can of worms?

**Comment by maranomynet** [comment]
BTW2: For now I'm hacking my way around this by doubling all my redirect path templates 

`'/media/:path*'`  
`'/media/:path*//:path2+'`

**Comment by blakeembrey** [comment]
> ...or would that open some other can of worms?

It does, but it can work. I'd have to ask what happens with this `/` outside of matches - does it act differently compared to within matches? What about `/x/:foo`? Could that match `/x/` now? Or do we expect the empty segment to only apply on repeated parameters?

Overall, I think the simpler approach is just to pre-process the URL instead. Do `path = path.replace(/\/+/, '/')` to normalize it once.

**Comment by blakeembrey** [comment]
> I'd prefer not having to know if/when collapsing double slashes is safe.

Gotcha, I guess you can't normalize the URL in this case entirely, but I think you could still do something along the lines of matching with the normalized path and using the original path to redirect.

**Comment by maranomynet** [comment]
My expectation was that the empty segment applied on repeated (i.e. `:foo+` and `:foo*`) parameters only.

Just to be clear, I consider this a fairly minor issue, since there is a workaround available. It's kind of ugly but works.
But it was not the expected behavior, and in my case it wasn't instantly obvious that some of the redirects where broken.
