### ISSUE TITLE
Help with regex - working with 0.1.7, not working with 3.1.0

### ISSUE THREAD

**Issue by carolpettirossi** [pillarjs/path-to-regexp#198]
Hello, 

I'm trying to use the following regex:
``` 
/:path((graduate-employers|institutions)/[^\/]+)/advice
``` 

in order to match these paths:
```
/graduate-employers/abc/advice
/institutions/abc/advice
```

When I use 0.1.7 version the regex works fine. However, if I upgrade to 3.1.0 it doesn't. 

Can someone help me with this?

**Comment by sariag** [comment]
I wouldn't recommend using the delimiter as part of the segment. A better approach would be to organize your regex as follows:
```javascript
const path = "/(graduate-employers|institutions)/:id/advice";
```

Then you can capture the values like this:
```javascript
const path = "/(graduate-employers|institutions)/:id/advice";
const regexp = pathToRegexp(path);
const res = regexp.exec('/graduate-employers/abc/advice')
if (res) {
    console.log(res[1]); // graduate-employers
    console.log(res[2]); // abc
}
```

**Comment by blakeembrey** [comment]
The recommendation by @sariag should work perfectly for you based on your original regex, let us know if you have more questions though!
