### ISSUE TITLE
Paths like `/foo(/bar)?`

### ISSUE THREAD

**Issue by gigabo** [pillarjs/path-to-regexp#200]
Hi!

We have some paths like `/foo(/bar)?` intended to match either `/foo` or `/foo/bar`.

These stopped working as of b6eac3f61af840d04266e1618f051b616d4ead7e.

Before: `/^\/foo(?:(\/bar))?(?:\/)?$/i`

After: `/^\/fo(?:o(\/bar))?(?:\/)?$/i`

Is this type of path not supported? Should we specify it some other way?

Thanks!

Bo

**Comment by sariag** [comment]
It seems like your capturing group should not include the delimiter for the last segment to be optional `/foo/(bar)?`

**Comment by gigabo** [comment]
Hi @sariag. Thanks for the suggestion.

That actually _does_ appear to work. It produces `/^\/foo(?:\/(bar))?(?:\/)?$/i`.

That is surprising to me, though. The slash following `foo` in the input path does not appear to be optional.

Maybe I am expecting the input paths to be more regexp-like than I should?

BTW - I am working around this currently by setting `{whitelist: "/"}` in options. I hope I am not shooting myself in the foot with this.

**Comment by blakeembrey** [comment]
The answer by @sariag is correct. The paths are not regexes, they are a format described in the README based on Express.js originally. Whitelist would also make it act like the previous version as you’ve noted.

**Comment by gigabo** [comment]
Okay, I see. I will stick with the whitelist, then. I have hundreds of paths configured by dozens of developers, so making it act like the previous version sounds much more appealing than trying to upgrade everything. :)

Thanks!
