### ISSUE TITLE
How to use `()` in Custom Match Parameters?

### ISSUE THREAD

**Issue by doubleKGe** [pillarjs/path-to-regexp#211]
For example:
If I write it like this:
```
path: ':code([^\/]+?/[^\/]+?/[^\/]+?)?'
```
It's true
but If I write it like this:
```
path: ':code(([^\/]+?)/([^\/]+?)/([^\/]+?))?'
```
It will not live up to expectations

So I want to ask how to use `()` in Custom Match Parameters?

**Comment by blakeembrey** [comment]
It should throw an error telling you what you need to do. It needs to be non-capturing. Here’s an example I found online for non-capturing groups: https://javascript.info/regexp-groups#non-capturing-groups-with

**Comment by blakeembrey** [comment]
This is also only allowed in V3 or higher.

**Comment by doubleKGe** [comment]
@blakeembrey  sorry, I still can't solve it, I tried to do the following, but I got an error
```js
const keys = []
pathToRegexp('/foo/:a((a)?bc)', keys)
```
error:
```
TypeError: Capturing groups are not allowed at 8
```
I need your help ,Thanks!
