### ISSUE TITLE
Do not consider `:number` as a valid variable name

### ISSUE THREAD

**Issue by ehmicky** [pillarjs/path-to-regexp#213]
`:variable` where the name includes only digits should not be included as variables. This is because of port numbers being prefixed with a colon in URLs.

```js
> pathToRegexp.parse('/localhost:80/:test')
[
  '/localhost',
  {
    name: '80',
    prefix: '',
    suffix: '',
    pattern: '[^\\/#\\?]+?',
    modifier: ''
  },
  {
    name: 'test',
    prefix: '/',
    suffix: '',
    pattern: '[^\\/#\\?]+?',
    modifier: ''
  }
]
```

I think this library is meant to be used only on the path (and query + hash) part of an URL, not the origin. However this might still be a good idea to support port numbers just in case.

**Comment by blakeembrey** [comment]
This library does not divine intent from how you wrote your path. A numeric key is perfectly valid. You will need to escape the `\:` if you want this to work right now.

**Comment by blakeembrey** [comment]
In a future revision it may be possible to restrict the key to starting alphabetically (e.g. JS identifier rules), but I worry a tiny bit about whether it'd cause confusion looking at that path. I.e. if you looked at that path without knowing the "rules", would you assume `:80` is a bug waiting to happen anyway?

**Comment by ehmicky** [comment]
I am misusing this library by allowing users to use `:variable` inside the origin as well, which is the reason behind my request. I understand this is a misuse though so it cannot be supported :+1: 

Escaping colons with backslashes worked around the problem.

**Comment by blakeembrey** [comment]
Sorry for the confusion. The token definitely isn’t the best overall once you start considering the entire path. It’d possible this could be made configurable, but that fragmentation might cause more confusion. Let me know if you have any ideas for a backward compatible solution!

**Comment by ehmicky** [comment]
There are definitely some issues using this beyond the path, query and hash. 

The main issue is that `:` is used for schemes (`http:`), userinfo (`username:password@`) and port (`:80`).

According to [RFC 3986](https://tools.ietf.org/html/rfc3986#section-3) the `{ } / # ?` characters must be escaped inside the scheme, username, password, hostname and port.

However that is not the case for `.` (used as default prefix together with `/` in this library).

Also that is the case for `:` for all the above with one catch: it is allowed unescaped in the username and password in RFC 3986 but not in the WHATWG URL spec.
