### ISSUE TITLE
TypeScript can't determine type of pathToRegexp

### ISSUE THREAD

**Issue by kmurph73** [pillarjs/path-to-regexp#216]
TS doesn't know the type of `pathToRegexp` when importing, EG:
```typescript
import pathToRegexp from 'path-to-regexp'
```

Steps to reproduce:
* `mkdir test && cd test`
* `yarn add path-to-regexp`
* `touch blah.ts`
* `code .`
*  then paste `import pathToRegexp from 'path-to-regexp'` into `blah.ts` ... TS can't figure out the type of `pathToRegexp`

Thank you!

**Comment by blakeembrey** [comment]
Here's the code in case that helps understand what's happening: https://github.com/pillarjs/path-to-regexp/blob/7b4078db2cfc929eb287432be0ecd3798b0de820/src/index.ts#L609.

**Comment by kmurph73** [comment]
Oh, duh, thanks (had copy/pasted that import from some JS that I was translating to TS)
