### ISSUE TITLE
Confusion on the methods

### ISSUE THREAD

**Issue by Haroenv** [pillarjs/path-to-regexp#217]
Hey! This package looks amazing for our use case where we want be able in one function write to the URL, and in the other read from it. However I found it somewhat confusing which functions to use. Now I have this:

```js
const { match, compile } = require("path-to-regexp");

// example URL format, configurable
const format = 'q/:query?/brands/:brand?';
const toPath = compile(format, { encode: encodeURIComponent })
const urlToParts = match(format, { decode: decodeURIComponent })

// our final API
const routing = {
  createURL(params) { // object -> string
    return toPath(params);
  }, 
  parseURL(url) {  // string -> object
    return urlToParts(url).params;
  },
};

const url = routing.createURL({ brand: 'something' })

console.log('url is: ' + url)

const params = routing.parseURL(url)

console.log('params were: ' + JSON.stringify(params))
```

I want to confirm that I'm using the API correctly. I'm mostly unsure about the difference between `pathToRegex`  and `match`. In the readme we could add something about the use case of writing, then parsing the same URL, I'm willing to write that once I definitely understand the  distinction. 

Thanks!

**Comment by blakeembrey** [comment]
The usage looks correct to me. If you’re using the new APIs, you don’t need the older RegExp based API - it’s there because that’s what this package was designed for and most people still use it that way.

**Comment by Haroenv** [comment]
That makes total sense! I think I was mostly  confused since the readme explains the regex methods first, which makes it seem like they're the preferred API. Thanks!

**Comment by jonchurch** [comment]
@Haroenv Feel free to close if you're satisfied 👍 

Also, if you feel the docs could be improved please do submit a PR to help others

**Comment by Haroenv** [comment]
I can’t think of a direct way to make this more clear for now, so thanks already!

**Comment by Haroenv** [comment]
If you're interested, here's the use case in full: https://github.com/algolia/instantsearch.js/pull/4324 I was a little confused on how to find which parameters _are actually used_, since the configuration is dynamic there.

Also wondering if it really makes sense to have the same path to all three functions. I might have caused it to parse three times instead of one (can you give the result of parse to the other functions? not clear from the docs for me)

Thanks!

**Comment by blakeembrey** [comment]
@Haroenv You can use `tokensToFunction`, then pass tokens into `tokensToFunction` (which is what `compile` does internally, also also pass them to `tokensToRegexp` and `regexpToFunction` (which is what `match` is doing internally). Apologies that the internals aren't as well documented, happy to accept improvements!

**Comment by Haroenv** [comment]
Ah, that’s interesting, would avoid doing the operation multiple times, thanks!

**Comment by Haroenv** [comment]
I think a schema on how the methods are used could help?
