### ISSUE TITLE
How to ignore `https://` in `^6.x`?

### ISSUE THREAD

**Issue by stnwk** [pillarjs/path-to-regexp#218]
Hi :) Thanks for your work on this project!

I have a question regarding migrating from `5.x` to `6.x`:

```tsx
const { compile } = require("path-to-regexp")
const build = compile('https://someurl.com/post/:postId');

build({ postId: 123 });
```

In `5.x` this code would work without a problem, correctly ignoring the `https://` protocol, starting with `6.x` however it doesn't work anymore and instead throws: `TypeError: Missing parameter name at 5`

I get it tries to find a named parameter after `https:` - my question is, how can I work around it? I've seen something regarding `encodeURIComponent` in the release notes, but couldn't figure it out.

Can you help?

Thank you very much :)

**Comment by jonchurch** [comment]
Good catch! I'm not sure there is currently a way to ignore the `https://` part of your URL string. This library is meant specifically to work with paths, not full URLs.

That is at the very least a breaking change that should be added to the changelog or something.

You can use the built in [Node.js URL class](https://nodejs.org/api/url.html#url_the_whatwg_url_api) to get the pathname from the URL and then concat the `origin` onto it afterwards.

```js
const { URL } = require('url');
const { compile } = require('path-to-regexp');

const urlString = 'https://someurl.com/post/:postId';

const buildFullUrl = url => opts => {
  const { origin, pathname } = new URL(url);
  const buildPath = compile(pathname);

  return `${origin}${buildPath(opts)}`;
};

const build = buildFullUrl(urlString);

console.log(build({ postId: 123 }));
```

**Comment by stnwk** [comment]
Nice workaround, thank you! 
That works for me :)

Agreed, would be good idea to add this to the change log and let others know about it too!

**Comment by blakeembrey** [comment]
You can also use a backslash to escape the colon, I’m not sure if that’s acceptable in your use-case though.

**Comment by blakeembrey** [comment]
The note in the change log for 6.0 related to this is “ Tokens in an unexpected position will throw an error”, let me know if there’s a clearer way to phrase it that would make sense to you, or whether you just want more examples.

**Comment by stnwk** [comment]
> Tokens in an unexpected position will throw an error

Hm, I guess now that you're pointed me to that sentence it makes sense - my problem that I wasn't even sure what I was looking for when going through the changelog and that sentence didn't catch my attention meaning it was very easy to overlook for me.

Maybe it's fine if you add a bold "Breaking:" before it, so that it's really easy to scan:

**Breaking:** Tokens in an unexpected position will throw an error


## Working solution
Anyways, since I needed a working solution in the browser that could handle both full urls with `http(s)://` and partial pathnames like `/post/:postId`, here's what I came up with based on your input:

```tsx
import { compile } from "path-to-regexp";
import URL from "url-parse";

const compilePath = (path: string) => (options: object) => {
  if (path.startsWith("http://")) {
    throw new Error("Please use https!");
  }

  if (path.startsWith("https://")) {
    const { origin, pathname } = new URL(path);
    const buildURL = compile(pathname);
    const url = `${origin}${buildURL(options)}`;

    return url;
  }

  const buildURL = compile(path);
  const url = buildURL(options);

  return url;
};

it("should work for partial url paths", () => {
  const buildURL = compilePath("/post/:postId");
  const url = buildURL({ postId: 123 });

  expect(url).toBe("/post/123");
});

it("should work for partial url paths", () => {
  const buildURL = compilePath("https://test.com/post/:postId");
  const url = buildURL({ postId: 123 });

  expect(url).toBe("https://test.com/post/123");
});
```

Hope it helps someone, closing this issue!
