### ISSUE TITLE
how to match all

### ISSUE THREAD

**Issue by cole-dda** [pillarjs/path-to-regexp#221]
/app1/:name 

/app1/a/b/c   ==>  name=a/b/c
/app2/a/b/d ===> name=a/b/d

**Comment by jonchurch** [comment]
Check out the docs section about [zero or more and one or more](https://github.com/pillarjs/path-to-regexp#zero-or-more).

`/app1/:name+` for one or more. Matches `app1/a` and `app1/a/b/c`
`/app1/:name*` for zero or more. Mathches `/app1/` and `app1/a/b/c`
