### ISSUE TITLE
Make optional match with + suffix

### ISSUE THREAD

**Issue by rienswagerman** [pillarjs/path-to-regexp#226]
Hi, I have a question. What is the way to make :id+ optional in this path?

```
/:id+/viewer/:image_index(\\d+)
```

I've tried this in vue router, but that only matches '/viewer/1', and not '/something/viewer/1':
```
/(:id+/)?viewer/:image_index(\\d+)
```
   
Thanks.

**Comment by blakeembrey** [comment]
You should be able to use `*`:

```
/:id*/viewer/:image_index(\\d+)
```
