### ISSUE TITLE
Capturing groups

### ISSUE THREAD

**Issue by tomsonpl** [pillarjs/path-to-regexp#229]
Hi, first of all big thanks for your work ;)  
I am using your library to parse my kind of complicated friendly URL. 

Do you think it is / would be possible to have a regexp like this? I mean including captured groups.  

`const priceRegex = "(cena)?(-od-:price_0(\\d+))?(-do-:price_1(\\d+))?(-zl)?";`

I am trying to work around it, however this would be very useful in the future.

Thanks in advance,

**Comment by mastermatt** [comment]
There is a recent PR to add named capture groups here https://github.com/pillarjs/path-to-regexp/pull/225

**Comment by blakeembrey** [comment]
I believe this is basically already supported if you replace the outer `()` with `{}`, e.g. `{-od-:price_0(\\d+)}?`. It allows for a custom prefix and suffix.
