### ISSUE TITLE
Travis after_script coverage script issue

### ISSUE THREAD

**Issue by DamianKu** [pillarjs/path-to-regexp#230]
In travis.yml file after_script looks like this
`after_script: "npm install coveralls@3 && npm run coverage | coveralls"`

There is not `coverage` run script in package.json so this throws an error in Travis
```
$ npm install coveralls@3 && npm run coverage | coveralls
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
+ coveralls@3.1.0
added 6 packages from 17 contributors and audited 1172 packages in 9.25s
found 40982 vulnerabilities (40962 low, 17 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details
npm ERR! missing script: coverage
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2020-07-18T14_29_29_205Z-debug.log
[error] "2020-07-18T14:29:29.227Z"  'error from lcovParse: ' 'Failed to parse string'
[error] "2020-07-18T14:29:29.229Z"  'input: ' ''
[error] "2020-07-18T14:29:29.229Z"  'error from convertLcovToCoveralls'
/home/travis/build/pillarjs/path-to-regexp/node_modules/coveralls/bin/coveralls.js:19
      throw err;
      ^
Failed to parse string
```

~Changing `npm run coverage` to `npm run specs` should fix this issue.~

https://www.npmjs.com/package/coveralls#jest

`after_script` should look like this: `"npm install coveralls@3 && npm run specs && coveralls < coverage/lcov.info"`

And because Travis runs `test` script which triggers `specs` - `npm install coveralls@3 && coveralls < coverage/lcov.info` could be enough

**Comment by blakeembrey** [comment]
Thanks for the catch! It's been fixed with https://github.com/pillarjs/path-to-regexp/commit/8b0ae94f9ada4705a6144d639088b058f52bf75d.
