### ISSUE TITLE
Any chance that we can use it on deno-land?

### ISSUE THREAD

**Issue by samsan1212** [pillarjs/path-to-regexp#232]
Bear with me if it is a stupid question.

Is there any chance that we can use this nice library on `deno` environment?

It would be very nice to have this library on deno.

**Comment by blakeembrey** [comment]
I think it could be done fairly easily, but I’m not familiar with using Deno myself. Do you want to submit a PR or test if it already works? It’s only one TypeScript file today so I suspect there shouldn’t be much change needed.

**Comment by blakeembrey** [comment]
Also, just to clarify, I assume you're specifically talking about registering it with https://deno.land instead of any other deno registry right?

**Comment by blakeembrey** [comment]
I've published it here: https://deno.land/x/path_to_regexp@v6.2.0/index.ts

Can you let me know if that works as expected in deno?

**Comment by lucacasonato** [comment]
@blakeembrey Just tried it and it is working great :-)

**Comment by samsan1212** [comment]
> 
> 
> Also, just to clarify, I assume you're specifically talking about registering it with https://deno.land instead of any other deno registry right?

yes yes, thank you very much. It works great.
