### ISSUE TITLE
Path matching repeating set of chars

### ISSUE THREAD

**Issue by Doc999tor** [pillarjs/path-to-regexp#233]
Hi, question: I use `Path-to-regexp` in `Express`  (it's v0.1.7)  
I want to match path like: /1,2,3,456,7890 - only digits and commas in any quantity, starting with digits
The naive path for it is: `/:ids(\d+[,\d]*)`, it compiles to: `/^\/(?:(\d+[,\d](.*)))\/?$/i` definitely not the regex I meant   
I test it with: http://forbeslindesay.github.io/express-route-tester/   
What is the correct way to write it right?  
Thanks

**Comment by Doc999tor** [comment]
Anybody can explain how to apply `*` modifier to a set of characters `[,\d]`?

**Comment by blakeembrey** [comment]
You can use `{0,}`.

**Comment by Doc999tor** [comment]
Thanks
Can I read about it elsewhere? Documentation about `*` and character sets? Any other rules of custom regex compilation?

**Comment by blakeembrey** [comment]
This is just a bug in a legacy version that cannot be fixed, there’s not much to read about.
