### ISSUE TITLE
How to match /foo/create OR /foo/:id?

### ISSUE THREAD

**Issue by realnot** [pillarjs/path-to-regexp#235]
I would like to match both urls as title. If :id is not passed as parameter, then match `create`. I tried something similar: `(:id?|create)` without success. I would like to match the following urls:

`/foo/123/` (the :id param can be alphanumeric)
`/foo/create/`

`/foo/123/create` <-- not valid
`/foo/create/123` <-- not valid

**Comment by blakeembrey** [comment]
You can pass an array of paths. You cannot put a param inside a matching group.
