### ISSUE TITLE
how to use in vue-router

### ISSUE THREAD

**Issue by Epic-Deno** [pillarjs/path-to-regexp#237]
vue-router official documents recommend me to use uses path-to-regexp as its path matching engine,but i can not find any example about using it, colud you privide me some examples?

**Comment by blakeembrey** [comment]
I don’t know anything about Vue so won’t be able to help you. One recommendation would be sharing the link you found this so I have a reference to help you. I’m going to close this out as an issue, but feel free to open a discussion instead!

**Comment by Epic-Deno** [comment]
thanks
