### ISSUE TITLE
Suggestion: Use named groups

### ISSUE THREAD

**Issue by aapoalas** [pillarjs/path-to-regexp#240]
As title suggests, ptr could compile eg. `:param` into `(?<param>...stuff...)` to make the parameter retrieval as close to automatic as possible.

**Comment by blakeembrey** [comment]
Please check for existing issues before creating a new one: https://github.com/pillarjs/path-to-regexp/issues/159.

TL;DR is that you can use `match` and this library needs to support systems without support for named capturing groups. Also named capturing groups won’t do extra stuff like decode your parameters.

**Comment by davidbonnet** [comment]
@blakeembrey Would it be considered to have `pathToRegex` support an option (e.g. `'groups'`) that would output a regex with named groups? The use case would be to simplify the creation of regexes by leveraging the path syntax:

```js
function path(pattern) { return pathToRegex('/:param1/:param2', { groups: true }) }

matchUrl(path('/:param1/:param2'), (request) => {
  const { matches } = request
  // Do something with matches.param1 and matches.param2
})
```

**Comment by blakeembrey** [comment]
@davidbonnet I think that's totally reasonable, open to accepting a PR. 

On the other hand, I think most people should not be using the regex directly. Maybe we should just emphasize the non-regex usage instead? What's the use-case of this over the `match` function?
