### ISSUE TITLE
how handle different extensions

### ISSUE THREAD

**Issue by daniloab** [pillarjs/path-to-regexp#242]
Hi,

Im trying to handle .png on my route, but I cannot do it with the following cod:

```
const regexpNumbers = pathToRegexp('/api/image/:id\\.(png)?');
```

If the .png don't exist should work and, if exist should work only if be `.png`

I created this simple script to test it:

```
import { pathToRegexp } from 'path-to-regexp';

(async () => {
  const regexpNumbers = pathToRegexp('/api/image/:id\\.(png)?');

  const withOutPng = regexpNumbers.exec(
    '/api/image/f655d48c-70e5-442f-8113-214692af5434',
  );

  const withDot = regexpNumbers.exec(
    '/api/image/f655d48c-70e5-442f-8113-214692af5434.',
  );

  const withPng = regexpNumbers.exec(
    '/api/image/f655d48c-70e5-442f-8113-214692af5434.png',
  );

  // eslint-disable-next-line
  console.log('withOutPng', withOutPng);

  // eslint-disable-next-line
  console.log('withDot', withDot);

  // eslint-disable-next-line
  console.log('withPng', withPng);
})();
```
The const `withDot` it is just for example and shows that works with the dot alone.

But, in my case should work the const `withOutPng` and `withPng`

I got the following result: 
<img width="516" alt="Screen Shot 2021-01-27 at 17 58 22" src="https://user-images.githubusercontent.com/19939822/106053196-478c4480-60c9-11eb-961a-91791dbc69ad.png">

how to do the `.png` optional?

**Comment by blakeembrey** [comment]
From https://github.com/pillarjs/path-to-regexp#custom-prefix-and-suffix, you can do `/api/image/:id{.png}?` or `/api/image/:id(.png)`? You could also just get rid of the `\\` in your string and it'd work too.
