### ISSUE TITLE
Params object has no prototype

### ISSUE THREAD

**Issue by lesjames** [pillarjs/path-to-regexp#244]
I ran into an issue with the params object being returned from match. I do an equality check on the params object and it was causing an error because the params object is being created without a prototype.

https://github.com/pillarjs/path-to-regexp/blob/b39edd433c173257062883f58867feecee660fd4/src/index.ts#L399

See some common issues when an object is created with no prototype.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create#custom_and_null_objects

**Comment by dougwilson** [comment]
This is to help mitigate the risks of [prototype pollution](https://codeburst.io/what-is-prototype-pollution-49482fc4b638).

**Comment by lesjames** [comment]
Ah, good to know. Thank you.
