### ISSUE TITLE
Wrong version installed

### ISSUE THREAD

**Issue by filway** [pillarjs/path-to-regexp#253]
Use the command: npm install path-to-regexp --save

Then the installed version is always 0.1.7

**Comment by blakeembrey** [comment]
I don’t get this behavior and latest on NPM is 6.2.0: https://www.npmjs.com/package/path-to-regexp. Do you have anything special about your setup that is pointing `latest` to a different release? You might want to open this issue on NPM.

**Comment by tom-saetran** [comment]
I get the same issue on NPM 7.20.0, it installs 0.1.7 by default, and judging by the downloads on your nom site, this happens to the MAJORITY of installs!

**Comment by blakeembrey** [comment]
> judging by the downloads on your npm site

0.1.7 is the version that comes with express, so seems expected. There's nothing else to change this and if you have a bug it's due to how NPM works and not anything I control.

**Comment by blakeembrey** [comment]
Can you provide a demo, replication, or video? Make sure to include any versions of dependencies for testing. Just saying something happens but without a way to replicate it doesn't help me help you, and 2 people out of millions of downloads sounds like the issue could be somewhere other than here.

**Comment by blakeembrey** [comment]
Here's the behavior I see FWIW, seems unlikely to help debug anything though:

```
~/Projects/tmp
❯ npm i path-to-regexp

added 1 package, and audited 44 packages in 731ms

found 0 vulnerabilities

~/Projects/tmp
❯ npm ls | grep path-to-regexp
├── path-to-regexp@6.2.0
```
