### ISSUE TITLE
Match not exported when using in TypeScript projects

### ISSUE THREAD

**Issue by joshtwist** [pillarjs/path-to-regexp#254]
When using path-to-regexp in my typescript project I can see the pathToRegExp, parse and compile functions but the match function is missing in the declarations.

**Comment by joshtwist** [comment]
Duh, using wrong version.

**Comment by tobilg** [comment]
@joshtwist I'm having the same problem, what did you change to fix this?

**Comment by joshtwist** [comment]
I don't know how, but I managed to pull a really old version of path-to-regexp. I manually updated the version in package.json to the latest and 'match' was there \o/

**Comment by tobilg** [comment]
Apparently that was my Problem as well. I did a npm i path-to-regexp, and version ^0.17.2 ended up in my package.json

Very strange.
