### ISSUE TITLE
Custom parameter length

### ISSUE THREAD

**Issue by tgbv** [pillarjs/path-to-regexp#258]
How to match a route of which parameter must have a certain length? For instance, "locale" must be exactly two characters and the following expression doesn't match:
```js
/route/:locale({2})/something-else
```

**Comment by kettanaito** [comment]
Hey, @tgbv.

You can use a regular expression group to specify the length of the parameter:

```js
var { match } = require("path-to-regexp")

const fn = match('/route/(.{2})/foo')
fn('/route/en/foo')
// {path: "/route/en/foo", index: 0, params: Object {0: "en"}}
```

> Note that you cannot combine named parameters and repetition. The "locale" parameter will be available as the first (`0`) unnamed parameter.
