### ISSUE TITLE
incorrect group value for `:name*` pattern

### ISSUE THREAD

**Issue by wanderview** [pillarjs/path-to-regexp#260]
If you run:

```javascript
const { pathToRegexp } = require('path-to-regexp');
pathToRegexp(':name*')
```

You will get this regexp:

```javascript
/^([^\/#\?]+?)*[\/#\?]?$/i
```

This regexp does not produce a proper matched group value, though.  From devtools:

```
var r = /^([^\/#\?]+?)*[\/#\?]?$/
undefined
r.exec('foobar')
(2) ['foobar', 'r', index: 0, input: 'foobar', groups: undefined]
```

The matched value is "r" instead of "foobar".

I think path-to-regexp should instead make the current grouping in the regexp non-matching and add a matching group around the repeating `*` modifier.  Like this:

```javascript
/^((?:[^\/#\?]+?)*)[\/#\?]?$/i
```

This is my plan for [fixing this in URLPattern](https://bugs.chromium.org/p/chromium/issues/detail?id=1243773).

**Comment by kettanaito** [comment]
I’ll add “+” scenario later next week as well.

**Comment by wanderview** [comment]
> I think the fix should also be applied for :name?

You can ignore this feedback from me above.  You are indeed correct we don't need the extra non-capturing group for the optional modifier.

**Comment by jeffmcaffer** [comment]
FWIW, I'd love a fix for this as well. Just stumbled on the problem. At least for me it seems to only happen with no leading '/'. So you can work around the problem by prefixing the pattern and target with a '/'. Bit of a hassle but seems to work. 
Otherwise, awesome library! Thanks.
