### ISSUE TITLE
Code base seems to be non-formatted with Prettier

### ISSUE THREAD

**Issue by kettanaito** [pillarjs/path-to-regexp#262]
The library is using Prettier to format the changes via `lint-staged` and `npm run prettier` command. When doing so, however, it formats the entire file, distorting the commit's diff. This makes contributing to the project extremely tedious.

I believe the reason for that is the lack of the explicit Prettier configuration that'd tell Prettier how to format the code. It must be detecting some of my other Prettier configurations and formatting the code base accordingly. 

## Solution

Let's add an explicit `.prettierrc` configuration so that the formatting on the commit hook would produce a consistent result.

**Comment by frank-dspeed** [comment]
i Would love to simply add a normal tsconfig.json here as typescript is the most advanced linter for JS at present it supports JSDOC types so we do not even need to transpil and all this stuff to get typechecking and also type definitions as also can enforce code formarting via tslint or something else.

i am strong against moving the codebase it self to .ts files

**Comment by blakeembrey** [comment]
Reformatted in the mega commit https://github.com/pillarjs/path-to-regexp/commit/b45871bb2e844d6ec05f13ddb76dceb52ac6d8c1. I'm taking a look at your PR finally and will rebase if I can 😄

**Comment by kettanaito** [comment]
Thank you, @blakeembrey!
