### ISSUE TITLE
"http://" prefix not be supported?

### ISSUE THREAD

**Issue by Anna-mm** [pillarjs/path-to-regexp#264]
```
const regexp = pathToRegexp("http\://www.example.com/:pageid"); // error
const regexp = pathToRegexp("http://www.example.com/:pageid"); // error

regexp.exec("http://www.example.com/123");
```

error message：throw new TypeError("Missing parameter name at " + i);

**Comment by blakeembrey** [comment]
JavaScript would require you to use two backslashes in a string since that's how escapes work. Otherwise you're just escaping the `:` for JavaScript and not this library.
