### ISSUE TITLE
How would I match a path disregarding the query?

### ISSUE THREAD

**Issue by AaronBeaudoin** [pillarjs/path-to-regexp#265]
I want to rewrite a path starting with `/some/path` whether or not it has a trailing slash (or a sub route), and ignores the query, simply copying it to the new path unchanged.

```
/some/path          --> /other/path
/some/path/         --> /other/path/
/some/path?a=b      --> /other/path?a=b
/some/path/?a=b     --> /other/path/?a=b
/some/path/sub      --> /other/path/sub
/some/path/sub/     --> /other/path/sub/
/some/path/sub?a=b  --> /other/path/sub?a=b
/some/path/sub/?a=b --> /other/path/sub/?a=b
```

I haven't been able to figure out how to do this with `path-to-regexp`.

**Comment by carloschneider** [comment]
Any suggestions here?

**Comment by blakeembrey** [comment]
This package does not support query parameters. I can't comment even on what is being used to rewrite here, but if it used `strict: true` it'd take into account the trailing slashes.
