### ISSUE TITLE
regex match fail

### ISSUE THREAD

**Issue by wengeezhang** [pillarjs/path-to-regexp#275]
'/person/([1-9]{0,})' matches '/person/12'.
but '/person/([1-9]{0,}s\d)' fails match '/person/12s1'.
why

**Comment by dougwilson** [comment]
From the readme:

> Tip: Backslashes need to be escaped with another backslash in JavaScript strings.

**Comment by wengeezhang** [comment]
![image](https://user-images.githubusercontent.com/4355382/163515447-a79ac371-60f4-4844-be8e-317f2c8d572b.png)

**Comment by sant123** [comment]
https://expressjs.com/en/guide/routing.html
