### ISSUE TITLE
Next dynamic route with spread (...) throws 'Unexpected MODIFIER at 70, expected END'

### ISSUE THREAD

**Issue by PSoltes** [pillarjs/path-to-regexp#278]
Hello,

this issue is linked to [@sls-next issue](https://github.com/serverless-nextjs/serverless-next.js/issues/2433), but unfortunately we are not getting any response from them.

Issue appears when dynamic paths like `/api/files/[service-slug]/[product-group-slug]/[category-slug]/[...file-name]` are processed by @sls-next. The @sls-next package converts this path to `/api/files/:service-slug/:product-group-slug/:category-slug/:file-name*`, which throws error in path-to-regexp function due to asterisk(*) at the end. Is this bug or correct behaviour? (as i am not that experienced with express paths)

**Comment by blakeembrey** [comment]
Your problem would be that you can't use dashes as the variable names, you effectively have a route that ends in `-name*` which is invalid. If you changed it to an underscore it'd work.

**Comment by PSoltes** [comment]
@blakeembrey Thanks so much for answer, i'll open issue with @sls-next to add this to docs somewhere, cause dashes in next path variables are no problem. Again thanks so much.
