### ISSUE TITLE
end option does not work as expected

### ISSUE THREAD

**Issue by shinya-takahashi-sf** [pillarjs/path-to-regexp#281]
Thank you for this library.
When I test with the option `end: false`, it does not work as expected. Please check below.

```
pathToRegexp("abc",
    [],
    {
      start: false,
      end: false,
    }
)

returns the value below

/abc(?:[\/#\?](?=[]|$))?(?=[\/#\?]|[]|$)/i
```

```
/abc(?:[\/#\?](?=[]|$))?(?=[\/#\?]|[]|$)/i.test('abc')
true
→ This is expected.

/abc(?:[\/#\?](?=[]|$))?(?=[\/#\?]|[]|$)/i.test('123abc')
true
→ This is expected.

/abc(?:[\/#\?](?=[]|$))?(?=[\/#\?]|[]|$)/i.test('abc123')
false
→ This is supposed to be true but the outcome is false.
```

I assume the regex value has `|$` before `/i` and it causes this behavior.

**Comment by blakeembrey** [comment]
No, this is actually expected behavior. It’s matching up to a delimiter, so you need to have a slash or other delimiter character to match. I can update the documentation on the feature.

**Comment by blakeembrey** [comment]
Is there some place where you prefer the last behavior to be true over the current behavior?

**Comment by bagratina** [comment]
> Is there some place where you prefer the last behavior to be true over the current behavior?

for http request interceptor. it takes RegExp as url parameter for picking the requests, and the if the request url has searchParams it does not match
