### ISSUE TITLE
When parsed to tokens, why are backslashes stripped from pattern?

### ISSUE THREAD

**Issue by Lord-Kamina** [pillarjs/path-to-regexp#282]
When creating tokens out of a match, why does the lexer function skip `\` inside patterns? (For example, turning `\w+` into just `w+`?

**Comment by dougwilson** [comment]
It's not the lexer, it is javascript. See what the output is of `console.log('\w+')`.

> Tip: Backslashes need to be escaped with another backslash in JavaScript strings.

**Comment by Lord-Kamina** [comment]
> It's not the lexer, it is javascript. See what the output is of `console.log('\w+')`.
> 
> > Tip: Backslashes need to be escaped with another backslash in JavaScript strings.

Ah, makes sense. I didn't account for that, as I got here from a C++ port, with which we generally use raw strings. :P

Thanks for the quick reply!
