### ISSUE TITLE
`?` in optional capture group isn't connected to group in output - named param

### ISSUE THREAD

**Issue by MadLittleMods** [pillarjs/path-to-regexp#287]
### Expected goal

The goal is to make a route where `foo` optional between `A` and `B`:

![](https://user-images.githubusercontent.com/558581/202097870-a8e65145-4a90-4ebe-8c4a-a29539c38609.png)

### Bug

But using the following input gives a flawed output regex that groups `A` and `foo` together in the optional capture group.

Input:
```
/:time(A(foo)?B)
```

Output ❌:
```
/^(?:\/(A(foo))?B)\/?$/i
```

### Workaround

Workaround input is to wrap the optional capture group in another capture group:

Input:
```
/:time(A((foo)?)B)
```

Output (works sufficiently) ✅:
```
/^(?:\/(A((foo))?)B)\/?$/i
```

---

Input and output tested on http://forbeslindesay.github.io/express-route-tester/

**Comment by blakeembrey** [comment]
Your fix only works accidentally because of https://github.com/pillarjs/path-to-regexp/pull/286. You should be escaping the inner parentheses. This isn’t a bug, just confusion on what is happening here - your first closing paren is closing the entire regex.

What version are you using?

**Comment by blakeembrey** [comment]
Based on your outputs I’m fairly sure you’re testing with an unsupported version.

**Comment by MadLittleMods** [comment]
It looks like `express@4.18.2` is using `path-to-regexp@0.1.7`, see [`expressjs/express/package.json#L50`](https://github.com/expressjs/express/blob/8368dc178af16b91b576c4c1d135f701a0007e5d/package.json#L50) - Same as what's shown on http://forbeslindesay.github.io/express-route-tester/ but I see that this project is up to version `6.x` already so `express` is extremely out of date.

Sorry for not checking versions. I assumed they were using a relatively right version given their big note about using this project under https://expressjs.com/en/guide/routing.html#route-paths and even this project readme links the live demo as the [Express route tester](https://github.com/pillarjs/path-to-regexp#live-demo).

> Express uses [path-to-regexp](https://www.npmjs.com/package/path-to-regexp) for matching the route paths; see the path-to-regexp documentation for all the possibilities in defining route paths. [Express Route Tester](http://forbeslindesay.github.io/express-route-tester/) is a handy tool for testing basic Express routes, although it does not support pattern matching.

---


Trying to escape the inner parenthesis has no effect on getting the right grouping with that version `0.1.7`,

 - `/:time(A\(foo)?B)` -> Invalid path
 - `/:time(A\(foo\)?B)` -> `/^(?:\/(A\(foo\))?B)\/?$/i`

Looks good in `2.0.0` from the Express route tester, `/:time(A\(foo)?B)` -> `/^\/((?:A\\(foo\\)?B))(?:\/(?=$))?$/i`

It looks like the new mission is to post the issue in the `express` issue tracker and update `path-to-regexp` in `express`.

**Comment by dougwilson** [comment]
> It looks like the new mission is to post the issue in the express issue tracker and update path-to-regexp in express.

You probably want to try using the Express 5 release instead of Express 4 for an updated `path-to-regexp`.

**Comment by MadLittleMods** [comment]
@dougwilson It looks like [Express 5 doesn't use `path-to-regexp`](https://github.com/expressjs/express/blob/6faf26d59f00637e5c09c1d320df966ee28349ad/package.json) anymore (at least directly)? Maybe through the `router` sub-dependency which uses [`path-to-regexp@3.2.0`](https://github.com/pillarjs/router/blob/f175698f863bce0012798e1fd0a4c80f3ae06731/package.json#L16):

 - `pathToRegexp('/:time(A(foo)?B)')` -> `/^\/([^\/]+?)\((?:A(foo))?B\)(?:\/)?$/i` ❌
 - `pathToRegexp('/:time(A\\(foo\\)?B)')` -> `/^\/(A\\(foo\\)?B)(?:\/)?$/i` ❌ (close but extra `\`)
 
With the latest `path-to-regex@6.2.1`:

 - `pathToRegexp('/:time(A(foo)?B)')` -> `TypeError: Capturing groups are not allowed at 8`
 - `pathToRegexp('/:time(A\\(foo\\)?B)')` -> `/^(?:\/(A\(foo\)?B))[\/#\?]?$/i` ❌


@blakeembrey What's the correct input I should expect to work? What version are you seeing it work in?

**Comment by blakeembrey** [comment]
The latest version is the correct behavior.

**Comment by blakeembrey** [comment]
To be clearer too, none of these examples have extra backslashes either. I think you’re interpreting the JS strings incorrectly.

Since backslash is a special character you need another backslash to escape it. That’s why you’re seeing two when viewed as a string.

**Comment by MadLittleMods** [comment]
@blakeembrey Can you give an example?

I feel like I've tried all of variations for escaping the backslash (even 3 and 4 backslashes now)

**Comment by blakeembrey** [comment]
You aren’t allowed to use capturing groups within the regex section of the string for this library. It’s exactly what the latest version says which I meant is the correct behavior.

I’m kind of guessing that’s what you’re trying to do?

**Comment by blakeembrey** [comment]
You can make it a non-capturing group if that’s acceptable for your use case.

**Comment by MadLittleMods** [comment]
> You can make it a non-capturing group if that’s acceptable for your use case.

Thanks for noting this caveat! Works perfect in `path-to-regexp@6.2.1` 👌

 - `pathToRegexp('/:time(A(?:foo)?B)')` -> `/^(?:\/(A(?:foo)?B))[\/#\?]?$/i` ✅


#### And to note how it behaves in other versions (relevant for `express`):

 
`path-to-regexp@3.2.0`:

 - `pathToRegexp('/:time(A(?:foo)?B)')` -> `SyntaxError: Invalid regular expression: /^\/([^\/]+?)\((?:A(?\:foo))?B\)(?:\/)?$/: Invalid group`
 - Can't get workarounds or other variations to work
 
---

`path-to-regexp@0.1.7`:

 - `pathToRegexp('/:time(A(?:foo)?B)')` -> `/^(?:\/(A(?:foo))?B)\/?$/i` ❌
 - `pathToRegexp('/:time(A((?:(?:foo))?)B)')` -> `/^\/(?:(A((?:(?:foo)))?)B)\/?$/i` ✅
    - The workaround mentioned in the issue description of wrapping in an extra capture group also works with a non-capture group
