### ISSUE TITLE
SyntaxError: Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by arnaudjnn** [pillarjs/path-to-regexp#288]
I'm using the following regex to exclude some pathname:

`/((?!api|_next|favicon|styleguide).*)`

It's working well in Chrome but in Safari I have the following issue:

`SyntaxError: Invalid regular expression: invalid group specifier name`

Safari [doesn't support lookbehind yet](https://caniuse.com/js-regexp-lookbehind)

Whats the alternative?

**Comment by blakeembrey** [comment]
Looks like it works on the latest Safari version now, but there's no real way to support an unsupported regex feature in this library. You're just at the mercy of the browser engine for regex support.
