### ISSUE TITLE
The validate config in options is not work in compile function.

### ISSUE THREAD

**Issue by Mr-zhao-dy** [pillarjs/path-to-regexp#289]
when i use options as you show in README like this:
const toPathRaw = compile("/user/:id");
toPathRaw({ id: ":/" }, { validate: false }); //=> "/user/:/"
I got a error: TypeError: Expected "id" to match "[^\/#\?]+?", but got ":/"

if I fix my code like below,options  works.
const toPathRaw = compile("/user/:id",{ validate: false });
toPathRaw({ id: ":/" });

**Comment by blakeembrey** [comment]
Thanks for the flag, I've fixed it in https://github.com/pillarjs/path-to-regexp/commit/c7ec332e87d8560673884d5629e1cb23cb03cb87.
