### ISSUE TITLE
throw new TypeError(`Unexpected ${nextType} at ${index}, expected ${type}`)

### ISSUE THREAD

**Issue by SoulNaturalist** [pillarjs/path-to-regexp#290]
Error
![image](https://user-images.githubusercontent.com/58743402/216850298-13f684ec-33b8-4231-a8a5-27668ceae53e.png)

My code

```typescript
import * as Koa from 'koa';
import * as Router from 'koa-router';

const app = new Koa();
const router = new Router();

router.get('/*', async (ctx) => {
    ctx.body = 'Hello World!';
});

app.use(router.routes());

app.listen(3000);
```

I started my app:

```
npx ts-node app.ts
```

And get that error...
How i can solve that?

**Comment by blakeembrey** [comment]
That’s not a valid route for this library. Please read the README. You can do `(.*)` instead.

**Comment by SoulNaturalist** [comment]
It was in the Koa examples, strange that it can't be done, thanks anyway!

**Comment by blakeembrey** [comment]
It's from an earlier release that used to allow that instead of `(.*)`. It's something that's been discussed as adding back, but nothing has really been implemented on that front.
