### ISSUE TITLE
Regex for non-negative integers only matches two or more digits

### ISSUE THREAD

**Issue by floscher** [pillarjs/path-to-regexp#292]
I usually like to use this Regex to match all positive integers (without 0 and leading zeros): `[1-9][0-9]*`

But when I write this in express `4.18.2`:
```typescript
router.get("/:id([1-9][0-9]*)", …);
```
Then it only matches IDs with at least two digits. Paths like `/2` get a 404 error with `Cannot GET /2`.

I'm not sure, what is the problem in this case, but it seems to me that this RegEx is not correctly evaluated.

**Comment by blakeembrey** [comment]
Express.js uses a very old version of this library where all `*` is converted into a wildcard match. So your regex there is actually more like `[1-9][0-9].*`.
