### ISSUE TITLE
Expected "id" to be a string error with release 7.0.0

### ISSUE THREAD

**Issue by Guymestef** [pillarjs/path-to-regexp#308]
Hello,

With the latest version, the following code is throwing a error now:

const toPath = compile("/user/:id");
toPath({ id: 123 });

// Expected behavior => "/user/123"
// Actual behavior => throw an error: Expected "id" to be a string

**Comment by joshkel** [comment]
@Guymestef, yes, this is one of the [breaking changes in 7.0.0](https://github.com/pillarjs/path-to-regexp/releases/tag/v7.0.0):

> * Stricter `compile` function - expects an array of strings in repeated parameters, and strings in non-repeated parameters

(We ran into it as well.)

**Comment by Curs3W4ll** [comment]
The README should be updated then, as the first example is using a number, and not a string

**Comment by blakeembrey** [comment]
I updated the README example here: https://github.com/pillarjs/path-to-regexp/commit/c9589365d0aba33b9745ebb9a909efdc50750007.

I can bump up the comment in the changelog, thanks for helping out @joshkel!
