### ISSUE TITLE
apply backtrack protection to version 3.2.0 because of nestjs

### ISSUE THREAD

**Issue by danielehrhardt** [pillarjs/path-to-regexp#317]
nestjs uses this package in version 3.2.0 could someone apply the patch: for this version. 

https://github.com/pillarjs/path-to-regexp/commit/29b96b4a1de52824e1ca0f49a701183cc4ed476f
https://github.com/nestjs/nest/issues/13955

**Comment by blakeembrey** [comment]
I also just created a 3.x branch in case you'd like to open a PR to port the patch. You need to be aware that the 0.1.x patch was a breaking change for some users, it's not possible to do this patch without a breaking change.

**Comment by blakeembrey** [comment]
I have published a [3.3.0](https://github.com/pillarjs/path-to-regexp/releases/tag/v3.3.0) with backtracking protection, but please beware that some use-cases may be broken as a result or have changed what it matches partially. I suspect over 99% of usage won't change, but feel free to let me know if something looks off.

**Comment by danielehrhardt** [comment]
> I have published a [3.3.0](https://github.com/pillarjs/path-to-regexp/releases/tag/v3.3.0) with backtracking protection, but please beware that some use-cases may be broken as a result or have changed what it matches partially (due to avoiding backtracking, e.g. `/:a-:b` with input `/1-2-3` now matches `1-2` and `3`, before `1` and `2-3`). I suspect over 99% of usage won't change, but feel free to let me know if something looks off.

<3

**Comment by pseudoralph** [comment]
@blakeembrey i'm curious, the CVE still lists the patched version as being >8 — although it's now been resolved in 3.3.0. How does/will this https://github.com/advisories/GHSA-9wv6-86v2-598j be updated to include v3.3.0 as a patched version to this vuln?

**Comment by blakeembrey** [comment]
I honestly don't know, I updated it on my side but it's the first time I've tried to do this after an audit and there's no way to manually update the published advisory now.

From https://github.blog/changelog/2019-12-20-edit-github-security-advisories-after-publish/, it looks like I'm waiting for a GitHub review manually:

> Edits of advisories in public repos are reviewed by GitHub. Upon review, we may use the updates to send security alerts to affected repositories and redistribute the advisory and its updates through [GitHub Advisory Database](https://github.com/advisories), our API, and our Atom feed.
