### ISSUE TITLE
Apply backtracking protection to version 1.8.0 due to "react-router-dom@5.3.4"

### ISSUE THREAD

**Issue by dotnet-fizzyy** [pillarjs/path-to-regexp#318]
Hi all!

Currently Git security bot raised an alert that `path-to-regexp` dependency with version _^1.7.0_ is vulnerable in `react-router-dom@5.3.4` (latest released `react-router-dom`) library.

Not really sure that `react-router-dom` with 5 version will be patched since team is completely focused on a new 6 version. Resolution with `8.0.0` in `package.json` does not help and breaks application on start with internal module error.

Would be perfect if this vulnerability will be fixed in terms of `1.x.x` package version since there is no chance to migrate to latest `react-router-dom` release on current moment in project I am working on.

Appreciate your attention!
Thanks!

**Comment by jackcurtis-te** [comment]
I was just getting this too but I set my resolution to be version `0.1.10` and it seems fine now.

**Comment by blakeembrey** [comment]
@dotnet-fizzyy It's extremely unlikely you are affected, see https://github.com/pillarjs/path-to-regexp/security/advisories/GHSA-9wv6-86v2-598j for the attack vector. It's also a non-issue as an attack vector in a browser, you'd just be DoSing your own browser.

Unfortunately I've spent months on this already and I don't have the income to support myself continuing to work on every release. If you would like to sponsor work on old versions that might be a possibility.

**Comment by stbenjam** [comment]
react-router-dom v5 hasn't seen any updates in 2 years.  While they claim [there's no end-of-life](https://github.com/remix-run/react-router/discussions/9637#discussioncomment-4245338), it seems likely it'll continue to rot.  We're going to just move to v6, but since it's a lot of effort  my app seems to work OK forcing the override in package.json for now.


```json
  "overrides": {
    "path-to-regexp": "^0.1.10"
  },
```

**Comment by stbenjam** [comment]
I filed https://github.com/remix-run/react-router/issues/11979, FWIW.  Not sure if they'll consider releasing a one-off of v5 with a fix.

**Comment by blakeembrey** [comment]
I have ported a fix into the 1.9.0 release and released it, it may break in extremely minor ways (e.g. the pattern has changed and "compile" can fail) but neither is likely to occur in regular usage of the library.

**Comment by stbenjam** [comment]
Thank you so much @blakeembrey ❤️

**Comment by fengmk2** [comment]
@blakeembrey Thanks a lot!

**Comment by dotnet-fizzyy** [comment]
@blakeembrey Appreciate your contribution and support, works perfectly, thanks a lot! 🥇
