### ISSUE TITLE
Apply advisory fix to v6

### ISSUE THREAD

**Issue by 75lb** [pillarjs/path-to-regexp#326]
Is it possible to apply a fix for this [current advisory](https://github.com/advisories/GHSA-9wv6-86v2-598j) to path-to-regexp version 6? We are not ready to upgrade to v7/v8 yet as we would need to replace features removed (e.g. regexp support) with hand-rolled alternatives..

**Comment by blakeembrey** [comment]
Duplicate of https://github.com/pillarjs/path-to-regexp/issues/323.
