### ISSUE TITLE
RegExp flag 's' not supported by older browsers

### ISSUE THREAD

**Issue by jlowcs** [pillarjs/path-to-regexp#330]
I have some concerns about using the latest major of `path-to-regexp` as it's now using the es2018 `s` flag for generated RegExp objects. In browsers that do not support this flag, the code will simply not work.

[caniuse](https://caniuse.com/mdn-javascript_builtins_regexp_dotall) 

Could there be an option to opt-out from this flag? Or could the library do some kind of feature detection to avoid this issue?

```js
const DOTALL_SUPPORTED = (() => {
  try {
    new RegExp('foo', 's');
    return true;
  } catch (e) {
    return false;
  }
})();

// ...

export function pathToRegexp(
  path: Path | Path[],
  options: PathToRegexpOptions & ParseOptions = {},
) {
  // ...
  const flags = DOTALL_SUPPORTED ? (sensitive ? "s" : "is") : (sensitive ? "" : "i");
  // ...
}
```

**Comment by blakeembrey** [comment]
The target output was updated to ES2020 as well here: https://github.com/pillarjs/path-to-regexp/blob/df39d6c30b2a8bdc9b8bda186f658cc89d47e44c/tsconfig.json#L4

This is why I wasn't too worried about shipping with `s` support. Is the target output also an issue for you or do you compile that down to something that can also run in these older browsers? If so, I can remove the flag, it's not particularly relevant to the usage of the library.

**Comment by blakeembrey** [comment]
Patched with https://github.com/pillarjs/path-to-regexp/commit/51dbd45e00043f082e3cf1857861e856c40a32f0, but I'll release after I hear about the target issue and whether that's a problem.

**Comment by jlowcs** [comment]
This specific kind of feature doesn't seem to be transpilable into an older ES version. If you use the dotall flag, TS just tells you you can't use it for that specific older ES target.

**Comment by blakeembrey** [comment]
I understand, but my question was: Is it an issue to continue targeting an output of ES2020 for you? Do you expect to file new issues because of it? It’s not an error today because ES2020 supported this flag and I’d like to know what I need to down level to at a minimum. Ideally I’d leave it as is though.

**Comment by blakeembrey** [comment]
Released a new version targeting ES2015 as the minimum: https://github.com/pillarjs/path-to-regexp/releases/tag/v8.2.0

**Comment by blakeembrey** [comment]
Keep in mind the code is currently still using generators: https://caniuse.com/es6-generators. So it improved compatibility by ~2%. Please let me know if you need further changes, and if it can be done without much impact to package size or complexity, I'm happy to give it a go.

**Comment by jlowcs** [comment]
> I understand, but my question was: Is it an issue to continue targeting an output of ES2020 for you? Do you expect to file new issues because of it? It’s not an error today because ES2020 supported this flag and I’d like to know what I need to down level to at a minimum. Ideally I’d leave it as is though.

It is not an issue to target ES2020 as long as the ES2020 features you're using are transpilable into older versions (by tsc, babel, swc...). For instance; generators and classes are transpilable, but regex flags are not.
