### ISSUE TITLE
Backtrack protection for version 5.x

### ISSUE THREAD

**Issue by dsehgal-atlassian** [pillarjs/path-to-regexp#334]
Hey everyone,
Can we release version 5.x with backtrack protection as well or is the version 5.x not supported anymore. 
Happy to create a pull request for same.

**Comment by blakeembrey** [comment]
Version 5.x is not supported, are you able to downgrade to a version I've already patched or upgrade? The release notes from [V4](https://github.com/pillarjs/path-to-regexp/releases/tag/v4.0.0) and [V5](https://github.com/pillarjs/path-to-regexp/releases/tag/v5.0.0) imply this should be relatively easy to downgrade, but I don't know how much of the library you are using.

**Comment by dsehgal-atlassian** [comment]
Thanks for the quick reply. I was able to downgrade it to 3.x
