### ISSUE TITLE
Odd patterns

### ISSUE THREAD

**Issue by soletan** [pillarjs/path-to-regexp#335]
I'm using path-to-regexp for processing routing configurations as part of a framework. The [compiled pattern](https://github.com/pillarjs/path-to-regexp/blame/d63f44bc54f2c6fe7d35dc77f8515622006bf7cb/src/index.ts#L506) seems to be odd based on options **end** and **trailing**.

If I get things right,

* setting **end** option to `false` is meant to create a regexp that's accepting paths starting with provided pattern. They may contain additional stuff.
* setting **trailing** option to `false` does not require a delimiter directly following the matching part of provided pattern nor does it fail if a delimiter is found nonetheless in case **end** is `false`, too.

Based on that,

* providing `false` for both options and pattern `/` creates a regexp `/^(?:\/)(?=\/|$)/` which is matching either `/` or anything starting with `//`. It isn't matching `/foo`. I would expect `/foo` to match as I explicitly set **end** to `false`. OTOH, I wouldn't expect `//` to match as it isn't a valid path.

  ```javascript
  expect( pathToRegExp( '/', { end: false, trailing: false } ).regexp.test( "/foo" ) ).toBeTrue();
  expect( pathToRegExp( '/', { end: false, trailing: false } ).regexp.test( "//" ) ).toBeFalse();
  ```

* providing `false` for both options and pattern `/foo`, the resulting regexp is `/^(?:\/foo)(?:\/$)?(?=\/|$)/` which is matching `/foo`, but _requires_ a delimiter following that pattern in case additional characters are found in a tested path which feels counterintuitive to having **trailing** set `false`.

  ```javascript
  expect( pathToRegExp( '/foo', { end: false, trailing: false } ).regexp.test( "/food" ) ).toBeTrue();
  ```

  However, I might be misreading the intention of **trailing** option here.

* when e.g. processing path names read from configurations of a framework based on path-to-regexp, I have to strip off trailing delimiters found in patterns to be converted with **pathToRegexp()** as a precaution to prevent broken patterns unless **end** option is `true`. For example, when I get `/foo/` to be converted with **end** option set `false`, `/foo/bar` isn't matching the resulting regexp `/^(?:\/foo\/)(?=\/|$)/` but `/foo//bar/` is.

  ```javascript
  expect( pathToRegExp( '/foo/', { end: false, trailing: false } ).regexp.test( "/foo/bar" ) ).toBeTrue();
  expect( pathToRegExp( '/foo/', { end: false, trailing: false } ).regexp.test( "/foo//bar" ) ).toBeFalse();
  ```

  If **trailing** option is `true` in this scenario. the resulting regexp is `/^(?:\/foo\/)(?:\/$)?(?=\/|$)/` which is accepting `/foo//` in addition to `/foo//bar`.

  ```javascript
  expect( pathToRegExp( '/foo/', { end: false, trailing: true } ).regexp.test( "/foo//" ) ).toBeFalse();
  ```

Of course, dealing with trailing delimiters found in provided input pattern may be something a consuming application is in charge of. This might circumvent all the issues described here. Passing empty string as input resulting from stripping off "trailing" slashes in `/` feels odd, though. Eventually, having an according statement in the docs regarding such a prerequisite would be preferrable at least.

**Comment by blakeembrey** [comment]
I think the only unclear case is `/`, but since no one has asked before I just left it alone. I think the easiest thing to do is map an input of `/` to an empty string, and it would work how you expect.

> requires a delimiter following that pattern in case additional characters are found in a tested path which feels counterintuitive to having trailing set false.

`trailing` only allows for an optional delimiter at the end to match. Otherwise `/foo/` would not match. That's all, nothing to do with matching `/food` - it should never do that since it'd be unexpected.

I'm not a huge fan of changing user inputs in this library, so I'd say it sounds like should just do `input.replace(/\/$/, '')` for everything to solve the issue. But when what happens if a user enters multiple slashes? Maybe `/+` for the regex?

**Comment by blakeembrey** [comment]
> setting trailing option to false does not require a delimiter directly following the matching part of provided pattern nor does it fail if a delimiter is found nonetheless in case end is false, too.

I'm having trouble reading this, maybe you can phrase it in the positive? I think it's a misunderstanding of this option but it's hard to tell. From the README:

> Allows optional trailing delimiter to match

That's all it's intended to do. Allow an optional (e.g. `/`) to match if it's at the end. It's common for applications to want `/foo` and `/foo/` to work the same, so that's what the flag does for you.

**Comment by blakeembrey** [comment]
For the two you have above as unacceptable, that's the intended behavior.

> This is due to the linked code is appending two separate regexp parts each individually matching an optional delimiter at the end of the provided path.

I don't think I understand this sentence. The `trailing` option is only adding `(?:/$)?` - one optional trailing slash. I'm not sure what you mean by two separate regex parts, maybe you're misunderstanding the regex?

> However, unlimited /\/+$/ should not be used there for it is backtracking thus vulnerable to ReDOS attacks.

Considering it's user input you're sanitizing, there's no real ReDoS attack vector. I wasn't proposing doing this on URL inputs.

It sounds like you might want slashes to match more than one? The `//` example is similar to asking `/foo//bar` to match against `/foo/bar`, which it doesn't today. I did make it an option in v7, but it seemed better to revert that and allow the user to pre-process paths by e.g. `path.replace(/\/+/g, '/')`.

**Comment by soletan** [comment]
> I don't think I understand this sentence. The `trailing` option is only adding `(?:/$)?` - one optional trailing slash. I'm not sure what you mean by two separate regex parts, maybe you're misunderstanding the regex?

Well, it's pretty obvious to me ... linked code is

```javascript
  let pattern = `^(?:${sources.join("|")})`;
  if (trailing) pattern += `(?:${escape(delimiter)}$)?`;
  pattern += end ? "$" : `(?=${escape(delimiter)}|$)`;
```

I see two potential additions to the pattern, right? One is adding an optional, non-capturing group matching the delimiter. The second one is adding a look-ahead assertion for end of string or another second delimiter following that optional delimiter. Hence it's matching a double-delimiter occurrence in a path. 

If that's intended behavior, well I don't mind as much as I don't mind you rejecting this issue accordingly. Though I can't think of a use case where two forward-slashes in a pathname are considered valid (except at the beginning to denote a hostname in a URL lacking its scheme part). They might not hurt for sure, that's why I considered this issue a minor one. Final assessment on this one is up to you, for sure.

**Comment by blakeembrey** [comment]
> Hence it's matching a double-delimiter occurrence in a path.

Except it's not. All you're testing is `(?=\/)`. You'd have the same result if you did `trailing: false` in those unacceptable versions. If you look at what matched, it was `/foo`, not `/foo//`.
