### ISSUE TITLE
pathToRegexp returns array with extra elements when used with optional path parts

### ISSUE THREAD

**Issue by esaborg** [pillarjs/path-to-regexp#339]
Keys array returned form `pathToRegexp` has unexpected entries when path has optional parts.

```
const { regexp, keys } = pathToRegexp(`/:one/:two/:three`);
// keys: (as exptected)
// [
//    { type: 'param', name: 'one' },
//    { type: 'param', name: 'two' },
//    { type: 'param', name: 'three' }
//  ]
```

When one part is changed to optional, keys array unexpectedly grows. I'd expect both cases to return keys array with 3 entries.
```
const { regexp, keys } = pathToRegexp(`/:one{/:two}/:three`);
// keys:
// [
//    { type: 'param', name: 'one' },
//    { type: 'param', name: 'two' },
//    { type: 'param', name: 'three' },
//    { type: 'param', name: 'one' },
//    { type: 'param', name: 'three' }
//  ]
```

**Comment by blakeembrey** [comment]
This is by design, the keys match the result of the `regexp`. I can open a PR to document this but I'd recommend using `match` instead.

**Comment by mxngls** [comment]
@blakeembrey would you mind elaborating on the imperative behind that design decision? As a user this seems quite unintuitive. A more ergonomic API might be to instead include the optional parameter with it's proper type i.e `group` and then other remaining parameters only once. Right now there is no way to know which of the returned parameters were optional and which were not.
