### ISSUE TITLE
express-route-tester breaks in certain cirumstances

### ISSUE THREAD

**Issue by sateffen** [pillarjs/path-to-regexp#43]
Heyho

Maybe it belongs here, I hope so: https://forbeslindesay.github.io/express-route-tester/ breaks under some circumstances...

Setup a route like `/test/:optVar?/:var` and a path like `/test/aVar`. This results in a result array looking like `["/test/aVar", undefined, "aVar"]` which crashes while escaping the results.

    Uncaught TypeError: Cannot read property 'replace' of undefined (index:9)

If you've got any questions left, let me know.

**Comment by blakeembrey** [comment]
Hi @sateffen! Thanks for the report and although it's not the exact repo to report it, I've fixed it up and created a PR for you :smile: Fixed with https://github.com/ForbesLindesay/express-route-tester/pull/2
