### ISSUE TITLE
publish to npm?

### ISSUE THREAD

**Issue by TooTallNate** [pillarjs/path-to-regexp#45]
It seems the npm package is still the deprecated `component/path-to-regexp`. Ideally we should have npm point to this package instead. What npm username do I need to add for publishing to be possible? Cheers!

**Comment by TooTallNate** [comment]
Actually nevermind... it appears that somebody published v0.1.4 of the old deprecated repo, and so the `latest` tag on the npm repo was pointing to that instead of the published v1.0.3. I've fixed this, so we can probably close this now.

**Comment by blakeembrey** [comment]
@TooTallNate Sorry, that was my fault. How did you fix up the `latest` pointer?

**Comment by TooTallNate** [comment]
It was something like `npm tag path-to-regexp@1.0.3 latest` IIRC
