### ISSUE TITLE
URL parameters behind a variable

### ISSUE THREAD

**Issue by rottmann** [pillarjs/path-to-regexp#47]
this will work (with / behind var1)
`/some/path/:var1/?fixed_var=fixed_value`

this not
`/some/path/:var1?fixed_var=fixed_value`

**Comment by blakeembrey** [comment]
@rottmann This library was never intended to even parse a string with query parameters. I'll need some more information to work this out though. What is the path/options you are using and what is the intended behaviour?

**Comment by rottmann** [comment]
Using the lib in my apidoc project
https://github.com/apidoc/apidoc/

An example output is here: http://apidocjs.com/example/
You can send a sample request to an url, the url can have the `:params`

@weikinhuang report an issue https://github.com/apidoc/apidoc/issues/226 because he use urls with `:params` and `?variables....`

**Comment by blakeembrey** [comment]
You can use a backslash to escape the question mark, but it's an optional flag for params (https://github.com/pillarjs/path-to-regexp#optional).
