### ISSUE TITLE
Ability to convert tokens to regex.

### ISSUE THREAD

**Issue by rill-js** [pillarjs/path-to-regexp#52]
The #parse method returns an array of tokens, it would be cool if we could pass in those tokens to get a regex again.

It would be useful to merge multiple parsed paths.

I could do a PR if anyone else things this is a good idea.

**Comment by blakeembrey** [comment]
@rill-js Great thought and easy enough to expose since that's what is already happening. Just curious, any thoughts on what you'd use it for?

**Comment by rill-js** [comment]
Currently i'm creating a nested router, and the paths need to be merged to their parents as they are created. It would be a bit easier this way since I could just merge arbitrary tokens rather than worrying about repeating segments and "/".

More of a convenience really but it be more efficient than rebuilding and re-parsing each regex every time. Also pretty easy to implement.

**Comment by blakeembrey** [comment]
@rill-js Could you review https://github.com/pillarjs/path-to-regexp/pull/53 and let me know if that's simple enough for you to use?
