### ISSUE TITLE
Bug with index property and arrays in 0.1.5

### ISSUE THREAD

**Issue by dougwilson** [pillarjs/path-to-regexp#55]
Hi! It looks like there is a bug in the new `index` feature of 0.1.5 when given arrays:
```
$ node -pe 'require("path-to-regexp/package").version'
0.1.5

$ node -pe 'var k=[],r=require("path-to-regexp")(["/user/:user/poke","/user/:user/pokes"],k);k'
[ { name: 'user', optional: false, index: 0, _offset: 7 },
  { name: 'user', optional: false, index: 0, _offset: 7 } ]
```
As you can see in the output above, both entries are marked as `index = 0`, when one of them should actually be `index = 1`.

**Comment by blakeembrey** [comment]
Thanks, I'll check it out ASAP :+1:

**Comment by blakeembrey** [comment]
@dougwilson Would you be willing to take a quick look at https://github.com/pillarjs/path-to-regexp/pull/56? I managed to take a different approach that requires no changes from Express (in fact, you can simplify the code since there's no more `undefined` params - kind of like `1.x`).

**Comment by dougwilson** [comment]
Looks great!

**Comment by blakeembrey** [comment]
@dougwilson Whoops, forgot to update the previous edit because I ended up fixing that issue too - `undefined` shouldn't ever come out anymore.

**Comment by dougwilson** [comment]
> Whoops, forgot to update the previous edit because I ended up fixing that issue too - undefined shouldn't ever come out for a match index anymore.

haha, I figured as much from the code, so I just kinda ignored it :)
