### ISSUE TITLE
Regex Syntax

### ISSUE THREAD

**Issue by dschinkel** [pillarjs/path-to-regexp#61]
I'm using koa-controller.

Trying to get this to work, I've tried several variations of syntax here:

    '/countries/:countryUrlFriendlyName(/^[a-z-]+$/i)/states/:stateUrlFriendlyName(/^[a-z-]+$/i)/cities/:cityUrlFriendlyName(/^[a-z-]+$/i)': {to: 'city#findByCountryAndStateAndCityUrlFriendlyName'}

    '/countries/:(/^[a-z-]+$/i)/states/:(/^[a-z-]+$/i)/cities/:(/^[a-z-]+$/i)': {to: 'city#findByCountryAndStateAndCityUrlFriendlyName'}

    '/countries/(/^[a-z-]+$/i)/states/(/^[a-z-]+$/i)/cities/(/^[a-z-]+$/i)': {to: 'city#findByCountryAndStateAndCityUrlFriendlyName'}

I want to be able to allow any characters including if they have dashes between them.  For example I want to allow these types of urls incoming to the router:

/countries/united-states-of-america/states/illinois/cities/chicago
/countries/unitedstatesofamerica/states/illinois/cities/chicago

no luck so far, I'm sure I'm  just missing something here..what is it?

**Comment by blakeembrey** [comment]
@dschinkel You can't put JavaScript regexp literals into a string like that. It works by evaluating the parts inside the brackets as a regexp, there is a small example in the README (https://github.com/pillarjs/path-to-regexp#custom-match-parameters, looks like it might need some love).

What you probably want is:

```js
'/countries/:countryUrlFriendlyName([a-z-]+)/states/:stateUrlFriendlyName([a-z-]+)/cities/:cityUrlFriendlyName([a-z-]+)'
```

Let me know if that solves it for you.

**Comment by dschinkel** [comment]
damn sure did..thanks!

**Comment by dschinkel** [comment]
I can get some sleep now thanks to you  :)!
