### ISSUE TITLE
host-to-regexp

### ISSUE THREAD

**Issue by DylanPiercey** [pillarjs/path-to-regexp#62]
Is there any consideration to allow path-to-regexp to support generating host matching regexes? As far as I can tell all that would change is that the delimiter in the regs would go from `/` to `.`.

This would be pretty handy for node servers handling multiple domains/subdomains.

**Comment by dougwilson** [comment]
With `npm`, there is no reason two turn a module into a kitchen sink of functionality; i.m.o that sounds like a different module (the `vhost` module https://github.com/expressjs/vhost does something like that already, and can probably just start using that module if desired).

Up to @blakeembrey , ultimately :)

**Comment by DylanPiercey** [comment]
@dougwilson I tend to agree for sure. I was just playing around with it and path-to-regexp has a bit more utility than vhosts also it isn't tied to a framework. Was just wondering if this is something that could potentially be an easy win for this library.

**Comment by dougwilson** [comment]
RIght, but I'm a big :-1: to adding it to this lib, if only because the module is called _path_-to-regexp.

**Comment by blakeembrey** [comment]
@DylanPiercey Can you provide more information on what this would actually look like? Currently `path-to-regexp` kind of already supports the period as a delimiter since it's used for extensions.

**Comment by DylanPiercey** [comment]
@blakeembrey I did some more testing and it actually seems to work for everything. Originally I thought it didn't work with with regexes and matched subdomains but it looks like it does.

I'm going to close this thanks for your responses!
