### ISSUE TITLE
Regex with starting optional group after forward slash gives error

### ISSUE THREAD

**Issue by clshortfuse** [pillarjs/path-to-regexp#70]
I'm using express which uses path-to-regexp for URL routing.

If I use the following regex: 

    '/(apple-)?icon-:res(\\d+)x\\2.png'

I get the following error:

    Invalid regular expression: /^\/(?(?:([^\/]+?))-)?icon-(?:(\d+))x\2\.png\/?$/: Invalid group

Using escaped forward slash still gives an Invalid group error

Breaking it down to just

    '/(apple-)?'

gives

    /^\/(?(?:([^\/]+?))-)?\/?$/: Invalid group

My current workaround is to do the following: 

    '/?(apple-)?icon-:res(\\d+)x\\2.png'

**Comment by blakeembrey** [comment]
Express.js uses a legacy version with legacy behaviour such as this, there's not anything that can be done, I don't think, other than updating Express.js.

**Comment by blakeembrey** [comment]
Ah, even on the new version the regexp doesn't match properly because of the way you're doing an optional group. I'm going to reopen to support that on the stable branch, however I still don't believe there's anything that can be done on `0.1`. For reference, this is the RegExp on `1.x`:

```js
/^(?:\/(apple-))?icon-(\d+)x2\.png(?:\/(?=$))?$/i
```

**Comment by blakeembrey** [comment]
@clshortfuse I suggest using a RegExp with you're current version of Express. I'm playing around with a patch for the current version of `path-to-regexp`.
