### ISSUE TITLE
Do we really need isArray as a dependency ?

### ISSUE THREAD

**Issue by sakthiiv** [pillarjs/path-to-regexp#73]
After all the npm left-pad problem, do we require isArray ? Its just a single line of code .. `toString.call(arr) == '[object Array]'`

**Comment by blakeembrey** [comment]
Yes.

**Comment by blakeembrey** [comment]
Removing this breaks backward compatibility at this point, you're welcome to inline the code if you need to in a PR.

**Comment by wtgtybhertgeghgtwtg** [comment]
What browsers would be supported by a `2.0`?

**Comment by blakeembrey** [comment]
@wtgtybhertgeghgtwtg Well, there is no 2.0 yet, but most likely every browser that it does today and it'd just require polyfills for certain features instead.

**Comment by wtgtybhertgeghgtwtg** [comment]
Is a `2.0` planned?
