### ISSUE TITLE
"/:path(abc|xyz)*" doesn't produce the expected result.

### ISSUE THREAD

**Issue by marvinklein** [pillarjs/path-to-regexp#78]
```
node -pe 'require("path-to-regexp")("/:path(abc|xyz)*")'
{ /^(?:\/(abc|xyz(?:\/abc|xyz)*))?(?:\/(?=$))?$/i
  keys: 
   [ { name: 'path',
       prefix: '/',
       delimiter: '/',
       optional: true,
       repeat: true,
       pattern: 'abc|xyz' } ] }
```

The generated expression unexpectedly matches `/xyz/abc`, but not `/abc/xyz`.

**Comment by blakeembrey** [comment]
@marvinklein So the cause is because the generated RegExp is not wrapped in groups - so it's erroneously matching `/abc` or `/xyz/abc` or `/xyzxyz`. Fixed it in https://github.com/pillarjs/path-to-regexp/pull/79. Thanks for the catch!
