### ISSUE TITLE
Typings file not published with npm

### ISSUE THREAD

**Issue by tiagoroldao** [pillarjs/path-to-regexp#84]
The typings file in the repository isn't published in npm, as far as I could tell. Also, the only typings found elsewhere are the tsd typings for the deprecated path-to-regexp.

**Comment by blakeembrey** [comment]
Thanks. I've fixed it with https://github.com/pillarjs/path-to-regexp/commit/8e28bdd29e89f5bc366d112f36a7d9f0cc3adf37.
