### ISSUE TITLE
can't recognise path with minus

### ISSUE THREAD

**Issue by lookis** [pillarjs/path-to-regexp#89]
version: 1.5.3

like this: 
/path-to-regexp/:path-to-regexp

**Comment by blakeembrey** [comment]
Can you provide more detail on what "can't recognise path with minus" means? It looks like you were trying to use a dash for the parameter name. If you check the documentation, it states that you can only use word characters (`[A-Za-z0-9_]` - https://github.com/pillarjs/path-to-regexp#named-parameters).
