### ISSUE TITLE
Using a space as deilimiter with  end: false doesn't match paths that extend it

### ISSUE THREAD

**Issue by mees-** [pillarjs/path-to-regexp#96]
When creating a regex with `pathToRegexp('test is', keys, { delimiter: ' ', end: false })` the regex doesn't match paths that extend it like: `'test is testing'`

**Comment by blakeembrey** [comment]
Thanks. The delimiter was only used for parsing the tokens, not for reconstructing the RegExp from tokens. I'll add it as an option there too. Out of interest, what are you using this for? I didn't expect someone to use it like this, that's for sure 😄

**Comment by mees-** [comment]
I was making a framework for bots for discord (a voice and chat service) and i was using path-to-regexp to match the chat messages, where it's weird to use anything other than spaces to distinguish between parts of the message

**Comment by blakeembrey** [comment]
Ok. I'm not sure it'd work so great in that situation because you might have multiple spaces between words and other grammar, right?

**Comment by mees-** [comment]
that's possible, but i guess i can just filter out double spaces and the user will know they're talking to a bot so the commands would have to be written correctly
