### ISSUE TITLE
regex starting with parenthesis gets interpreted incorrectly

### ISSUE THREAD

**Issue by hellatan** [pillarjs/path-to-regexp#97]
I'm using an express app in this context and it seems that the issue comes down to this module. I'm using express@4.13.4 which uses path-to-regexp@0.1.7. I noticed that the current release for this module is 1.7.0, however.

The following route is something I'm trying to get my app to use:

```js
router.use('/(segment1|segment2|segment3)', someMethod);
```

Logically, I would expect the following routes to be visible to the app now:

- host.com/segment1
- host.com/segment2
- host.com/segment3

However, the app is unable to run at all which throws the following error:

```
SyntaxError: Invalid regular expression: /^\/(?(?:([^\/]+?))|segment2|segment3)\/?(?=\/|$)/: Invalid group
```

Notice how `segment1` is entirely ignored but changed into some other random regexp? The error is pointing to the underlying library of `at pathtoRegexp (...node_modules/path-to-regexp/index.js:128:10)` so i'm not sure if it's an issue with that module or if express is doing something to that route before it gets passed to that module.

This is the entire stack trace after my app tries to spin up:

```
SyntaxError: Invalid regular expression: /^\/(?(?:([^\/]+?))|jewelry|fashion|art)\/?(?=\/|$)/: Invalid group
    at RegExp (native)
    at pathtoRegexp (/site/node_modules/path-to-regexp/index.js:128:10)
    at new Layer (/site/node_modules/express/lib/router/layer.js:45:17)
    at Function.use (/site/node_modules/express/lib/router/index.js:464:17)
    at Object.<anonymous> (index.es.js:38:8)
```

the `index.es.js` reference is where the `router.use` method kicks off.

**Comment by blakeembrey** [comment]
Thanks. This is just one of a few long-standing issues with the `0.1.x` branch and I don't currently have any intention of fixing it. I believe I tried before, but doing so breaks some existing functionality that is expected to exist in `0.1.x`. Also, I don't believe unnamed parameters were ever a documented feature of `0.1.x` - try using `/:param(x|y|z)` instead.

**Comment by hellatan** [comment]
cool. thanks for the update. I didn't realize (nor did i try until @dougwilson suggested it) to use an actual regex in my route instead. That seemed to be a fine "workaround" for this issue.
