### ISSUE TITLE
Wildcard with exceptions

### ISSUE THREAD

**Issue by Dadibom** [pillarjs/path-to-regexp#99]
Hey! I'd love a way to use negative lookahead regexes in my paths, for example *(?!foo) to match everything but 'foo'.

However, this does not work. Output:
'Uncaught SyntaxError: Invalid regular expression: /^\/\:((?:?\!foo))(?:\/(?=$))?$/: Nothing to repeat'

Maybe there's already a way to do this that I don't know of?

**Comment by blakeembrey** [comment]
No, this isn't possible. Try using a RegExp instead.

**Comment by Dadibom** [comment]
Unfortunately it's not up to me as i'm using this through vue-router :(

**Comment by blakeembrey** [comment]
This library accepts regular expressions, if they are just passed through it should be fine.

**Comment by Dadibom** [comment]
Thank you for clarifying :)
